Repository ansible/ansible-documentation, pull requests merged in 2023-12, with the labels that each got.

#869 installation_guide/intro: update seealso with respect to communication
  docs/docsite/rst/installation_guide/intro_installation.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#707 add nox make session and revamp contribution docs
  README.md
  noxfile.py
Labels: doc builds, backport-2.15, backport-2.14, backport-2.16, tooling, merge_commit

#915 handlers notify example indentation fix
  docs/docsite/rst/playbook_guide/playbooks_handlers.rst
Labels: backport-2.15, backport-2.14, backport-2.13, new_contributor, backport-2.16

#856 Ansible 9: Follow ansible-core more closely
  docs/docsite/rst/roadmap/COLLECTIONS_9.rst
Labels: backport-2.15, sc_approval, backport-2.16

#929 Add Ansible community 9.1.0 porting guide
  docs/docsite/rst/porting_guides/porting_guide_9.rst
Labels: backport-2.16

#932 Add 2.14 and 2.15 CVE porting guide to 2.16
  docs/docsite/rst/porting_guides/porting_guide_core_2.14.rst
  docs/docsite/rst/porting_guides/porting_guide_core_2.15.rst
Labels: no_backport

#943 Improve module developing documenation for deprecation and linking
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
  docs/docsite/rst/dev_guide/module_lifecycle.rst
Labels: backport-2.15, backport-2.16

#941 Improve the last sentence in the 'Try it in staging first' section
  docs/docsite/rst/tips_tricks/ansible_tips_tricks.rst
Labels: backport-2.15, backport-2.16

#911 documentation_contributions: show how to set up a venv and remove outdated notes
  docs/docsite/rst/community/documentation_contributions.rst
Labels: backport-2.15, backport-2.14, backport-2.16, tooling

#910 Update windows_winrm.rst
  docs/docsite/rst/os_guide/windows_winrm.rst
Labels: techreview

#958 bump minimum antsibull-docs version to 2.6.0
  tests/constraints.in
  tests/requirements-relaxed.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: bug, doc builds, dependency_update

#882 Retroactively add a 2.15 porting guide note about handlers
  docs/docsite/rst/porting_guides/porting_guide_core_2.15.rst
Labels: techreview, backport-2.15, backport-2.16

#962 [stable-2.14] bump approved antsibull-docs version to 2.6.0
  tests/constraints.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: doc builds, no_backport, dependency_update

#965 Remove some scenario guides
  docs/docsite/rst/scenario_guides/cloud_guides.rst
  docs/docsite/rst/scenario_guides/guide_alicloud.rst
  docs/docsite/rst/scenario_guides/guide_online.rst
  docs/docsite/rst/scenario_guides/guide_oracle.rst
  docs/docsite/rst/scenario_guides/guide_packet.rst
  docs/docsite/rst/scenario_guides/guide_rax.rst
  docs/docsite/rst/scenario_guides/guide_scaleway.rst
  docs/docsite/rst/scenario_guides/guides.rst
Labels: no_backport

#954 clone-core.py: allow specifying custom branch and repo
  docs/bin/clone-core.py
Labels: backport-2.15, backport-2.14, backport-2.13, backport-2.16, tooling

#953 Add documentation for the custom Jinja2 global function `undef`
  docs/docsite/rst/playbook_guide/playbooks.rst
  docs/docsite/rst/playbook_guide/playbooks_filters.rst
  docs/docsite/rst/playbook_guide/playbooks_templating_now.rst
  docs/docsite/rst/playbook_guide/playbooks_templating_undef.rst
Labels: backport-2.15, backport-2.16

#976 Collection requirements: add seealso with link to Collection creator path
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
Labels: sc_approval, backport-2.16

#986 remove remaining network scenario guides
  docs/docsite/rst/scenario_guides/guide_infoblox.rst
  docs/docsite/rst/scenario_guides/guide_meraki.rst
  docs/docsite/rst/scenario_guides/guides.rst
  docs/docsite/rst/scenario_guides/network_guides.rst
  docs/docsite/rst/scenario_guides/scenario_template.rst
Labels: no_backport

#956 Fix argument_specs.yml example
  docs/docsite/rst/playbook_guide/playbooks_reuse_roles.rst
Labels: backport-2.15, backport-2.14, backport-2.13, backport-2.16

#639 [stable-2.16] ci: use Github App token to authenticate
  .github/workflows/labeler.yml
  .github/workflows/pip-compile-dev.yml
  .github/workflows/pip-compile-docs.yml
  .github/workflows/reusable-pip-compile.yml
  hacking/get_bot_user.sh
Labels: needs_triage, tooling

#640 [stable-2.15] ci: use Github App token to authenticate
  .github/workflows/labeler.yml
  hacking/get_bot_user.sh
Labels: backport-2.14, needs_triage, tooling
