Repository ansible/ansible-documentation, pull requests merged in 2023-09, with the labels that each got.

#355 noxfile: run typing session as part of lint session
  noxfile.py
Labels: no_backport

#342 [stable-2.15] Backport workflow automation
  .github/dependabot.yml
  .github/workflows/ci.yaml
  .github/workflows/reusable-nox.yml
  .isort.cfg
  .pip-tools.toml
  docs/docsite/rst/community/documentation_contributions.rst
  noxfile.py
  tests/constraints-base.in
  tests/constraints.in
  tests/formatters.in
  tests/formatters.txt
  tests/requirements-relaxed.in
  tests/requirements-relaxed.txt
  tests/requirements.in
  tests/static.in
  tests/static.txt
  tests/typing.in
  tests/typing.txt
Labels: doc builds, no_backport

#353 pr_labeler: add nag comment for issues and PRs without description
  hacking/pr_labeler/data/no_body_nag.md
  hacking/pr_labeler/label.py
  hacking/pr_labeler/requirements.txt
  tests/typing.txt
Labels: backport-2.15, backport-2.14, backport-2.13

#360 [stable-2.13] pr_labeler: add nag comment for issues and PRs without description (#353)
  hacking/pr_labeler/data/no_body_nag.md
  hacking/pr_labeler/label.py
  hacking/pr_labeler/requirements.txt
Labels: needs_triage

#359 [stable-2.14] pr_labeler: add nag comment for issues and PRs without description (#353)
  hacking/pr_labeler/data/no_body_nag.md
  hacking/pr_labeler/label.py
  hacking/pr_labeler/requirements.txt
Labels: needs_triage

#354 pr_labeler: allow setting custom repo via CLI
  hacking/pr_labeler/label.py
Labels: backport-2.15, backport-2.14, backport-2.13, needs_triage

#364 Fixes the error for ansible-doc in the tutorial
  examples/scripts/my_test.py
Labels: backport-2.15, backport-2.14

#313 [2.15] [issues #78]Update collection requirements links (#306)
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/communication.rst
  docs/docsite/rst/dev_guide/developing_collections_migrating.rst
  docs/docsite/rst/dev_guide/testing/sanity/import.rst
Labels: backport-2.14, sc_approval

#369 nox pip-compile: allow passing custom posargs
  noxfile.py
Labels: backport-2.15

#363 Add Forum banner
  docs/docsite/.templates/banner.html
Labels: backport-2.15

#322 adds sphinx-intl to requirements
  tests/requirements-relaxed.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: doc builds

#365 Update sphinx to 7.2.5 and remove constraint
  tests/constraints-base.in
  tests/constraints.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: doc builds

#268 installation_guide/installation_distros.rst: improve readability
  docs/docsite/rst/installation_guide/installation_distros.rst
Labels: DaWGs

#296 Host core docs on readthedocs
  .readthedocs.yaml
Labels: DaWGs, doc builds

#392 communication.rst: add forum info
  docs/docsite/rst/community/communication.rst
Labels: needs_triage

#405 build(deps): bump actions/checkout from 3 to 4 (#372)
  .github/workflows/ci.yaml
  .github/workflows/labeler.yml
  .github/workflows/reusable-nox.yml
Labels: backport-2.14, backport-2.13, needs_triage, dependency_update, tooling

#398 Bump for core 2.17
  docs/docsite/rst/community/development_process.rst
  docs/docsite/rst/porting_guides/core_porting_guides.rst
  docs/docsite/rst/porting_guides/porting_guide_core_2.17.rst
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: no_backport

#409 [stable-2.14] (build(deps): bump actions/checkout from 3 to 4 (#372))
  .github/workflows/ci.yaml
  .github/workflows/labeler.yml
Labels: needs_triage, dependency_update, tooling

#387 Update guide_gce.rst
  docs/docsite/rst/scenario_guides/guide_gce.rst
Labels: new_contributor

#406 Removing [] from --tags and --skip-tags
  docs/docsite/rst/playbook_guide/playbooks_tags.rst
Labels: new_contributor

#413 [stable-2.15] readthedocs configuration
  .readthedocs.yaml
Labels: backport-2.14, backport-2.13, needs_triage

#425 change banner for contributor summit
  docs/docsite/.templates/banner.html
Labels: backport-2.15, backport-2.16

#434 Add label to 'collections:' keyword
  docs/docsite/rst/collections_guide/collections_using_playbooks.rst
Labels: backport-2.15, backport-2.14, backport-2.13, needs_triage, backport-2.16

#439 run_community_ee_image: fix anchor
  docs/docsite/rst/getting_started_ee/run_community_ee_image.rst
Labels: needs_triage

#404 Ansible 9 roadmap: only do alphas after planned prereleases of ansible-core
  docs/docsite/rst/roadmap/COLLECTIONS_9.rst
Labels: sc_approval

#441 Fix undefined reference
  docs/docsite/rst/porting_guides/porting_guide_2.10.rst
  docs/docsite/rst/porting_guides/porting_guide_base_2.10.rst
Labels: needs_triage, backport-2.16

#438 communication.rst: Add Release Management WG info
  docs/docsite/rst/community/communication.rst
Labels: backport-2.15, backport-2.16

#445 Bump docs build dependencies, including upgrading antsibull-docs to 2.4.0
  tests/constraints.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: needs_triage, backport-2.16

#447 [stable-2.15] ci: refresh dev dependencies
  tests/static.txt
  tests/typing.txt
Labels: needs_triage

#452 Add Ansible community 9.0.0a1 porting guide
  docs/docsite/rst/porting_guides/porting_guide_9.rst
Labels: needs_triage, backport-2.16
