Repository ansible/ansible-documentation, pull requests merged in 2023-10, with the labels that each got.

#467 Bump antsibull-docs to 2.5.0
  tests/constraints.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: needs_triage

#449 [stable-2.14] Bump docs build dependencies, including upgrading antsibull-docs to 2.4.0
  tests/constraints.in
  tests/requirements.txt
Labels: doc builds

#448 [stable-2.15] Bump docs build dependencies, including upgrading antsibull-docs to 2.4.0
  tests/constraints.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: doc builds

#485 Update automationhub.rst #477
  docs/docsite/rst/reference_appendices/automationhub.rst
Labels: backport-2.15, needs_triage, backport-2.16

#431 Unify the Sphinx's `conf.py` files
  .gitignore
  docs/docsite/Makefile
  docs/docsite/Makefile.sphinx
  docs/docsite/rst/conf.py
  docs/docsite/sphinx_conf/2.10_conf.py
  docs/docsite/sphinx_conf/all_conf.py
  docs/docsite/sphinx_conf/ansible_conf.py
  docs/docsite/sphinx_conf/core_lang_conf.py
Labels: backport-2.16

#479 Fix for : Replace all occurrences of via to with #459
  docs/docsite/rst/community/steering/steering_committee_membership.rst
  docs/docsite/rst/dev_guide/developing_locally.rst
  docs/docsite/rst/dev_guide/developing_program_flow_modules.rst
  docs/docsite/rst/galaxy/dev_guide.rst
  docs/docsite/rst/inventory/implicit_localhost.rst
  docs/docsite/rst/inventory_guide/connection_details.rst
  docs/docsite/rst/inventory_guide/intro_patterns.rst
  docs/docsite/rst/network/user_guide/platform_ce.rst
  docs/docsite/rst/network/user_guide/platform_iosxr.rst
  docs/docsite/rst/plugins/become.rst
  docs/docsite/rst/plugins/connection.rst
  docs/docsite/rst/plugins/shell.rst
  docs/docsite/rst/plugins/strategy.rst
  docs/docsite/rst/porting_guides/porting_guide_7.rst
  docs/docsite/rst/roadmap/ROADMAP_2_5.rst
  docs/docsite/rst/roadmap/ROADMAP_2_6.rst
  docs/docsite/rst/vault_guide/vault_using_encrypted_content.rst
Labels: sc_approval

#482 [2.14] bump antsibull-docs to 2.5
  tests/constraints.in
  tests/requirements.txt
Labels: needs_triage

#483 [2.13]bump antsibull-docs to 2.5
  tests/constraints.in
  tests/requirements.txt
Labels: needs_triage

#500 Fix spelling errors in porting guides
  docs/docsite/rst/porting_guides/porting_guide_6.rst
  docs/docsite/rst/porting_guides/porting_guide_7.rst
Labels: new_contributor

#490 Replace i.e with that is
  docs/docsite/rst/porting_guides/porting_guide_2.10.rst
  docs/docsite/rst/porting_guides/porting_guide_3.rst
Labels: new_contributor

#502 Replacing filename with file name
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/documentation_contributions.rst
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
  docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
  docs/docsite/rst/dev_guide/developing_program_flow_modules.rst
  docs/docsite/rst/dev_guide/developing_python_3.rst
  docs/docsite/rst/dev_guide/style_guide/index.rst
  docs/docsite/rst/dev_guide/testing/sanity/ignores.rst
  docs/docsite/rst/dev_guide/testing/sanity/validate-modules.rst
  docs/docsite/rst/inventory_guide/intro_inventory.rst
  docs/docsite/rst/network/user_guide/cli_parsing.rst
  docs/docsite/rst/playbook_guide/playbook_pathing.rst
  docs/docsite/rst/playbook_guide/playbooks_conditionals.rst
  docs/docsite/rst/playbook_guide/playbooks_reuse.rst
  docs/docsite/rst/playbook_guide/playbooks_variables.rst
  docs/docsite/rst/playbook_guide/playbooks_vars_facts.rst
  docs/docsite/rst/plugins/inventory.rst
  docs/docsite/rst/reference_appendices/faq.rst
  docs/docsite/rst/reference_appendices/glossary.rst
Labels: sc_approval

#523 Fix Getting started EE guide
  docs/docsite/rst/getting_started_ee/build_execution_environment.rst
  docs/docsite/rst/getting_started_ee/run_execution_environment.rst
Labels: no_backport

#520 Update sanity test docs for devel
  docs/docsite/rst/dev_guide/testing/sanity/ansible-test-future-boilerplate.rst
  docs/docsite/rst/dev_guide/testing/sanity/boilerplate.rst
  docs/docsite/rst/dev_guide/testing/sanity/future-import-boilerplate.rst
  docs/docsite/rst/dev_guide/testing/sanity/index.rst
  docs/docsite/rst/dev_guide/testing/sanity/metaclass-boilerplate.rst
Labels: no_backport

#536 Renamed "user name" to "username" in .rst files
  docs/docsite/rst/community/collection_contributors/collection_integration_updating.rst
  docs/docsite/rst/dev_guide/style_guide/basic_rules.rst
  docs/docsite/rst/getting_started_ee/run_execution_environment.rst
  docs/docsite/rst/inventory_guide/connection_details.rst
  docs/docsite/rst/inventory_guide/intro_dynamic_inventory.rst
  docs/docsite/rst/inventory_guide/intro_inventory.rst
  docs/docsite/rst/network/getting_started/first_inventory.rst
  docs/docsite/rst/playbook_guide/playbooks_privilege_escalation.rst
  docs/docsite/rst/plugins/connection.rst
  docs/docsite/rst/reference_appendices/logging.rst
  docs/docsite/rst/scenario_guides/guide_aci.rst
Labels: backport-2.15, new_contributor, backport-2.16, hacktoberfest

#522 Add Arch installation instructions in the installation_distros documentation
  docs/docsite/rst/installation_guide/installation_distros.rst
Labels: backport-2.15, new_contributor, backport-2.16

#538 fix molecule link in contributor path page
  docs/docsite/rst/community/communication.rst
  docs/docsite/rst/community/contributor_path.rst
  docs/docsite/rst/community/other_tools_and_programs.rst
Labels: backport-2.15, backport-2.14, needs_triage, new_contributor, backport-2.16

#556 Add Ansible community 8.5.0 porting guide
  docs/docsite/rst/porting_guides/porting_guide_8.rst
Labels: backport-2.15, needs_triage, backport-2.16

#529 Integrate `docs/bin/*.py` files into the nox config
  .mypy.ini
  docs/bin/clone-core.py
  docs/bin/find-plugin-refs.py
  noxfile.py
Labels: backport-2.15, backport-2.16, tooling

#562 [stable-2.15] Integrate `docs/bin/*.py` files into the nox config (#529)
  .mypy.ini
  docs/bin/clone-core.py
  docs/bin/find-plugin-refs.py
  noxfile.py
Labels: needs_triage

#578 [2.15] Fix for : Replace all occurrences of via to with #459 (#479)
  docs/docsite/rst/community/steering/steering_committee_membership.rst
  docs/docsite/rst/dev_guide/developing_locally.rst
  docs/docsite/rst/dev_guide/developing_program_flow_modules.rst
  docs/docsite/rst/galaxy/dev_guide.rst
  docs/docsite/rst/inventory/implicit_localhost.rst
  docs/docsite/rst/inventory_guide/connection_details.rst
  docs/docsite/rst/inventory_guide/intro_patterns.rst
  docs/docsite/rst/network/user_guide/platform_ce.rst
  docs/docsite/rst/network/user_guide/platform_iosxr.rst
  docs/docsite/rst/plugins/become.rst
  docs/docsite/rst/plugins/connection.rst
  docs/docsite/rst/plugins/shell.rst
  docs/docsite/rst/plugins/strategy.rst
  docs/docsite/rst/porting_guides/porting_guide_7.rst
  docs/docsite/rst/roadmap/ROADMAP_2_5.rst
  docs/docsite/rst/roadmap/ROADMAP_2_6.rst
  docs/docsite/rst/vault_guide/vault_using_encrypted_content.rst
Labels: sc_approval

#582 [2.15] More info on delegation behaviours (#527)
  docs/docsite/rst/playbook_guide/playbooks_delegation.rst
Labels: needs_triage

#568 Update url in ConfigureRemotingForAnsible.ps1
  examples/scripts/ConfigureRemotingForAnsible.ps1
Labels: backport-2.15, backport-2.14, backport-2.16

#569 Testing collections guide: add GHA info and link to sample matrix
  docs/docsite/rst/dev_guide/developing_collections_testing.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#570 developing_collections_structure.rs: Fix link formatting
  docs/docsite/rst/dev_guide/developing_collections_structure.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#571 communication.rst: Add a link to the forum group list
  docs/docsite/rst/community/communication.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#599 corrected cli for help
  docs/docsite/rst/dev_guide/testing/sanity/validate-modules.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#489 Update PowerShell Codeblock
  docs/docsite/rst/os_guide/windows_performance.rst
Labels: techreview, backport-2.15, backport-2.14, new_contributor, backport-2.16

#446 Document how to bump dependencies
  README.md
Labels: backport-2.15, backport-2.16

#524 Add RST spellcheck
  .codespellignorelines
  .codespellignorewords
  .codespellrc
  .github/workflows/pip-compile-dev.yml
  .github/workflows/reusable-nox.yml
  README.md
  docs/docsite/rst/community/collection_contributors/collection_reviewing.rst
  docs/docsite/rst/community/committer_guidelines.rst
  docs/docsite/rst/dev_guide/developing_collections_distributing.rst
  docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
  docs/docsite/rst/dev_guide/developing_modules_in_groups.rst
  docs/docsite/rst/dev_guide/developing_plugins.rst
  docs/docsite/rst/dev_guide/migrating_roles.rst
  docs/docsite/rst/playbook_guide/index.rst
  docs/docsite/rst/playbook_guide/playbooks_advanced_syntax.rst
  docs/docsite/rst/playbook_guide/playbooks_conditionals.rst
  docs/docsite/rst/playbook_guide/playbooks_environment.rst
  docs/docsite/rst/playbook_guide/playbooks_filters.rst
  docs/docsite/rst/playbook_guide/playbooks_intro.rst
  docs/docsite/rst/playbook_guide/playbooks_reuse.rst
  docs/docsite/rst/playbook_guide/playbooks_tags.rst
  docs/docsite/rst/playbook_guide/playbooks_variables.rst
  docs/docsite/rst/scenario_guides/guide_aci.rst
  docs/docsite/rst/scenario_guides/guide_scaleway.rst
  docs/docsite/rst/vault_guide/vault_using_encrypted_content.rst
  noxfile.py
  tests/spelling.in
  tests/spelling.txt
Labels: backport-2.15, backport-2.16, tooling

#621 ci: use Github App token to authenticate
  .github/workflows/labeler.yml
  .github/workflows/pip-compile-dev.yml
  .github/workflows/pip-compile-docs.yml
  .github/workflows/reusable-pip-compile.yml
  hacking/get_bot_user.sh
Labels: no_backport, tooling

#623 [stable-2.15] Add RST spellcheck (#524)
  .codespellignorelines
  .codespellignorewords
  .codespellrc
  .github/workflows/reusable-nox.yml
  README.md
  docs/docsite/rst/community/collection_contributors/collection_reviewing.rst
  docs/docsite/rst/community/committer_guidelines.rst
  docs/docsite/rst/dev_guide/developing_collections_distributing.rst
  docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
  docs/docsite/rst/dev_guide/developing_modules_in_groups.rst
  docs/docsite/rst/dev_guide/developing_plugins.rst
  docs/docsite/rst/dev_guide/migrating_roles.rst
  docs/docsite/rst/playbook_guide/index.rst
  docs/docsite/rst/playbook_guide/playbooks_advanced_syntax.rst
  docs/docsite/rst/playbook_guide/playbooks_conditionals.rst
  docs/docsite/rst/playbook_guide/playbooks_environment.rst
  docs/docsite/rst/playbook_guide/playbooks_filters.rst
  docs/docsite/rst/playbook_guide/playbooks_intro.rst
  docs/docsite/rst/playbook_guide/playbooks_reuse.rst
  docs/docsite/rst/playbook_guide/playbooks_tags.rst
  docs/docsite/rst/playbook_guide/playbooks_variables.rst
  docs/docsite/rst/scenario_guides/guide_aci.rst
  docs/docsite/rst/scenario_guides/guide_scaleway.rst
  docs/docsite/rst/vault_guide/vault_using_encrypted_content.rst
  noxfile.py
  tests/spelling.in
  tests/spelling.txt
Labels: needs_triage

#633 ci pip-compile: remove environment key
  .github/workflows/pip-compile-dev.yml
  .github/workflows/pip-compile-docs.yml
Labels: needs_triage

#634 [stable-2.16] Codespell ignore inv 2.16
  .codespellrc
Labels: needs_triage

#636 ci pr_labeler: also use the app token for issues
  .github/workflows/labeler.yml
Labels: needs_triage, tooling, pr_labeler

#643 pr_labeler: stop adding new_triage labels to new PRs
  hacking/pr_labeler/label.py
Labels: backport-2.15, backport-2.14, backport-2.13, backport-2.16, tooling, pr_labeler

#514 pr_labeler: add warning for porting_guides changes
  hacking/pr_labeler/data/porting_guide_changes.md
  hacking/pr_labeler/label.py
Labels: no_backport, tooling, pr_labeler, merge_commit

#491 Changed it's to it is in all .rst files
  docs/docsite/rst/community/contributor_path.rst
  docs/docsite/rst/community/documentation_contributions.rst
  docs/docsite/rst/dev_guide/developing_collections_structure.rst
  docs/docsite/rst/dev_guide/developing_modules_checklist.rst
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
  docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
  docs/docsite/rst/dev_guide/developing_program_flow_modules.rst
  docs/docsite/rst/dev_guide/developing_python_3.rst
  docs/docsite/rst/dev_guide/overview_architecture.rst
  docs/docsite/rst/dev_guide/style_guide/grammar_punctuation.rst
  docs/docsite/rst/dev_guide/style_guide/spelling_word_choice.rst
  docs/docsite/rst/dev_guide/style_guide/voice_style.rst
  docs/docsite/rst/dev_guide/testing.rst
  docs/docsite/rst/inventory_guide/intro_inventory.rst
  docs/docsite/rst/network/getting_started/first_inventory.rst
  docs/docsite/rst/network/user_guide/network_debug_troubleshooting.rst
  docs/docsite/rst/playbook_guide/guide_rolling_upgrade.rst
  docs/docsite/rst/playbook_guide/playbooks_blocks.rst
  docs/docsite/rst/playbook_guide/playbooks_loops.rst
  docs/docsite/rst/playbook_guide/playbooks_reuse_roles.rst
  docs/docsite/rst/porting_guides/porting_guide_7.rst
  docs/docsite/rst/reference_appendices/YAMLSyntax.rst
  docs/docsite/rst/reference_appendices/faq.rst
  docs/docsite/rst/reference_appendices/glossary.rst
  docs/docsite/rst/reference_appendices/test_strategies.rst
  docs/docsite/rst/roadmap/COLLECTIONS_8.rst
  docs/docsite/rst/roadmap/COLLECTIONS_9.rst
  docs/docsite/rst/roadmap/ROADMAP_2_5.rst
  docs/docsite/rst/scenario_guides/guide_azure.rst
  docs/docsite/rst/scenario_guides/guide_gce.rst
  docs/docsite/rst/scenario_guides/guide_packet.rst
  docs/docsite/rst/scenario_guides/vmware_rest_scenarios/authentication.rst
  docs/docsite/rst/scenario_guides/vmware_rest_scenarios/create_vm.rst
Labels: sc_approval, new_contributor

#652 [stable-2.15] Changed it's to it is in all .rst files
  docs/docsite/rst/community/contributor_path.rst
  docs/docsite/rst/community/documentation_contributions.rst
  docs/docsite/rst/dev_guide/developing_collections_structure.rst
  docs/docsite/rst/dev_guide/developing_modules_checklist.rst
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
  docs/docsite/rst/dev_guide/developing_modules_general_windows.rst
  docs/docsite/rst/dev_guide/developing_program_flow_modules.rst
  docs/docsite/rst/dev_guide/developing_python_3.rst
  docs/docsite/rst/dev_guide/overview_architecture.rst
  docs/docsite/rst/dev_guide/style_guide/grammar_punctuation.rst
  docs/docsite/rst/dev_guide/style_guide/spelling_word_choice.rst
  docs/docsite/rst/dev_guide/style_guide/voice_style.rst
  docs/docsite/rst/dev_guide/testing.rst
  docs/docsite/rst/inventory_guide/intro_inventory.rst
  docs/docsite/rst/network/getting_started/first_inventory.rst
  docs/docsite/rst/network/user_guide/network_debug_troubleshooting.rst
  docs/docsite/rst/playbook_guide/guide_rolling_upgrade.rst
  docs/docsite/rst/playbook_guide/playbooks_blocks.rst
  docs/docsite/rst/playbook_guide/playbooks_loops.rst
  docs/docsite/rst/porting_guides/porting_guide_7.rst
  docs/docsite/rst/reference_appendices/YAMLSyntax.rst
  docs/docsite/rst/reference_appendices/faq.rst
  docs/docsite/rst/reference_appendices/glossary.rst
  docs/docsite/rst/reference_appendices/test_strategies.rst
  docs/docsite/rst/roadmap/COLLECTIONS_8.rst
  docs/docsite/rst/roadmap/ROADMAP_2_5.rst
  docs/docsite/rst/scenario_guides/guide_azure.rst
  docs/docsite/rst/scenario_guides/guide_gce.rst
  docs/docsite/rst/scenario_guides/guide_packet.rst
  docs/docsite/rst/scenario_guides/vmware_rest_scenarios/authentication.rst
  docs/docsite/rst/scenario_guides/vmware_rest_scenarios/create_vm.rst
Labels: merge_commit

#653 porting_guides: add porting_guide_9 to the index
  docs/docsite/rst/porting_guides/porting_guides.rst
Labels: backport-2.16

#549 Add forum info to collection maintainer guidelines
  docs/docsite/rst/community/maintainers_guidelines.rst
Labels: backport-2.15, backport-2.14, backport-2.16, Community maintainer

#607 Use a working exponential backoff example
  docs/docsite/rst/playbook_guide/complex_data_manipulation.rst
Labels: techreview, backport-2.15, backport-2.14, backport-2.16

#666 [stable-2.14] Rename tests/sanity.py to tests/checkers.py (#563)
  .github/workflows/ci.yaml
  tests/checkers.py
Labels: backport-2.13, tooling

#664 get_bot_user: use correct username in committer email
  hacking/get_bot_user.sh
Labels: no_backport, tooling

#671 Update example using special variables in resuce section of blocks
  docs/docsite/rst/playbook_guide/playbooks_blocks.rst
Labels: backport-2.15, backport-2.16

#677 Update shebang sanity test docs to match test
  docs/docsite/rst/dev_guide/testing/sanity/shebang.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#541 Update slicing in inventory pattern
  docs/docsite/rst/inventory_guide/intro_patterns.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#691 Update intro_inventory page
  docs/docsite/rst/inventory_guide/intro_inventory.rst
Labels: backport-2.15, backport-2.16

#669 communication.rst: other forum-related tweaks
  docs/docsite/rst/community/communication.rst
Labels: backport-2.15, backport-2.16

#685 [stable-2.14] Backport noxfile and other workflow changes
  .codespellignorelines
  .codespellignorewords
  .codespellrc
  .github/dependabot.yml
  .github/workflows/ci.yaml
  .github/workflows/reusable-nox.yml
  .isort.cfg
  .mypy.ini
  .pip-tools.toml
  README.md
  docs/bin/clone-core.py
  docs/bin/find-plugin-refs.py
  docs/docsite/rst/command_guide/intro_adhoc.rst
  docs/docsite/rst/community/communication.rst
  docs/docsite/rst/community/documentation_contributions.rst
  docs/docsite/rst/dev_guide/developing_plugins.rst
  docs/docsite/rst/playbook_guide/playbooks_filters.rst
  docs/docsite/rst/playbook_guide/playbooks_privilege_escalation.rst
  noxfile.py
  tests/constraints-base.in
  tests/constraints.in
  tests/formatters.in
  tests/formatters.txt
  tests/requirements-relaxed.in
  tests/requirements-relaxed.txt
  tests/requirements.in
  tests/spelling.in
  tests/spelling.txt
  tests/static.in
  tests/static.txt
  tests/typing.in
  tests/typing.txt
Labels: doc builds, tooling, merge_commit

#686 Drop reference of obsolete inventory script
  docs/docsite/rst/inventory_guide/intro_dynamic_inventory.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#706 documentation_contributions: use tests/checkers.py
  docs/docsite/rst/community/documentation_contributions.rst
Labels: backport-2.15, backport-2.14, backport-2.13, backport-2.16

#711 improve Ansible getting started diagram
  docs/docsite/rst/getting_started/index.rst
  docs/docsite/rst/images/ansible_basic.svg
  docs/docsite/rst/images/ansible_inv_start.svg
Labels: backport-2.16

#692 add changelog link to core support matrix
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.16

#668 Integrate docs checkers into the noxfile
  .github/workflows/ci.yaml
  .github/workflows/reusable-nox.yml
  README.md
  noxfile.py
Labels: doc builds, backport-2.15, backport-2.16, tooling, merge_commit

#730 nox and README: log PIP_CONSTRAINT value and add Dependency file docs
  README.md
  noxfile.py
Labels: backport-2.15, backport-2.14, backport-2.16, tooling, merge_commit

#749 Remove contributor summit banner
  docs/docsite/.templates/banner.html
Labels: backport-2.15, backport-2.16
