Repository ansible/ansible-documentation, pull requests merged in 2023-11, with the labels that each got.

#732 Remove dangling reference
  docs/docsite/rst/command_guide/intro_adhoc.rst
  docs/docsite/rst/playbook_guide/guide_rolling_upgrade.rst
  docs/docsite/rst/plugins/action.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#620 moar complitz tags docs
  docs/docsite/rst/playbook_guide/playbooks_tags.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#745 intro_installation: pass --include-injected in pipx upgrade example
  docs/docsite/rst/installation_guide/intro_installation.rst
Labels: backport-2.15, backport-2.16

#769 Replaced the AWX mailing list with the AWX Forum page.
  docs/docsite/rst/community/communication.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#756 set release version to 2.16
  docs/docsite/rst/conf.py
Labels: no_backport

#755 update versioning for 2.16
  docs/docsite/rst/conf.py
Labels: backport-2.15, backport-2.14, backport-2.16

#778 update headings and title instructions
  docs/docsite/rst/dev_guide/style_guide/index.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#757 Update the Note for certificate authentication with a TLS 1.3 connection in windows_winrm.rst
  docs/docsite/rst/os_guide/windows_winrm.rst
Labels: backport-2.15, backport-2.16

#787 Porting guide for 9.0.0b1
  docs/docsite/rst/porting_guides/porting_guide_9.rst
Labels: backport-2.16

#788 Add Ansible community 8.6.0 porting guide
  docs/docsite/rst/porting_guides/porting_guide_8.rst
Labels: backport-2.15, backport-2.16

#789 Rebuild Ansible 8.6.0 with purestorage.flasharray 1.21.0
  docs/docsite/rst/porting_guides/porting_guide_8.rst
Labels: no_backport

#785 communication.rst: update Docs WG reference
  docs/docsite/rst/community/communication.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#795 communication.rst: update MySQL WG to point to the forum group page
  docs/docsite/rst/community/communication.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#784 communication.rst: add EE group to the list of WGs
  docs/docsite/rst/community/communication.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#798 EOL 2.13 in the release and maintenance table
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#766 Update windows_setup.rst to fix link
  docs/docsite/rst/os_guide/windows_setup.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#819 Update developing_program_flow_modules.rst
  docs/docsite/rst/dev_guide/developing_program_flow_modules.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#822 update galaxy urls for networking docs
  docs/docsite/rst/network/user_guide/platform_ce.rst
  docs/docsite/rst/network/user_guide/platform_cnos.rst
  docs/docsite/rst/network/user_guide/platform_dellos10.rst
  docs/docsite/rst/network/user_guide/platform_enos.rst
  docs/docsite/rst/network/user_guide/platform_eos.rst
  docs/docsite/rst/network/user_guide/platform_eric_eccli.rst
  docs/docsite/rst/network/user_guide/platform_exos.rst
  docs/docsite/rst/network/user_guide/platform_frr.rst
  docs/docsite/rst/network/user_guide/platform_icx.rst
  docs/docsite/rst/network/user_guide/platform_index.rst
  docs/docsite/rst/network/user_guide/platform_ios.rst
  docs/docsite/rst/network/user_guide/platform_iosxr.rst
  docs/docsite/rst/network/user_guide/platform_ironware.rst
  docs/docsite/rst/network/user_guide/platform_junos.rst
  docs/docsite/rst/network/user_guide/platform_meraki.rst
  docs/docsite/rst/network/user_guide/platform_netvisor.rst
  docs/docsite/rst/network/user_guide/platform_nos.rst
  docs/docsite/rst/network/user_guide/platform_nxos.rst
  docs/docsite/rst/network/user_guide/platform_routeros.rst
  docs/docsite/rst/network/user_guide/platform_slxos.rst
  docs/docsite/rst/network/user_guide/platform_voss.rst
  docs/docsite/rst/network/user_guide/platform_vyos.rst
  docs/docsite/rst/network/user_guide/platform_weos4.rst
  docs/docsite/rst/network/user_guide/validate.rst
Labels: backport-2.15, backport-2.16

#828 communication.rst: remove inactive security WG info
  docs/docsite/rst/community/communication.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#825 Fix delegate_to details about inheriting vars from 'all'
  docs/docsite/rst/playbook_guide/playbooks_delegation.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#843 Add Ansible community 9.0.0 porting guide
  docs/docsite/rst/porting_guides/porting_guide_9.rst
Labels: backport-2.16

#831 add Ansible 9 changelogs
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.16

#832 Set release version to 9
  docs/docsite/rst/conf.py
Labels: backport-2.16

#799 update backport instructions to match 2.16
  docs/docsite/rst/community/development_process.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#827 sphinx: remove usage of deprecated notfound-page options
  docs/docsite/rst/conf.py
Labels: no_backport

#841 Update the information on RouterOS network connections
  docs/docsite/rst/network/user_guide/platform_routeros.rst
Labels: backport-2.15, backport-2.14, backport-2.13, backport-2.16

#598 Refs #340: Swap old 'CLA' for the DCO
  CONTRIBUTING.md
  DCO
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/contributor_license_agreement.rst
  docs/docsite/rst/community/developer_certificate_of_origin.rst
  docs/docsite/rst/community/getting_started.rst
  docs/docsite/rst/dev_guide/ansible_index.rst
  docs/docsite/rst/dev_guide/core_index.rst
  docs/docsite/rst/dev_guide/developing_modules_checklist.rst
Labels: backport-2.15, backport-2.14, sc_approval, backport-2.16

#852 [stable-2.16] Downgrade sphinx and fix 404 pages
  docs/docsite/rst/conf.py
  tests/constraints-base.in
  tests/constraints.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: doc builds, merge_commit

#878 add support for Ansible 9 intersphinx links
  docs/docsite/rst/conf.py
Labels: backport-2.16

#826 add ansible-galaxy to command cheatsheet
  docs/docsite/rst/command_guide/cheatsheet.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#836 update python versions in installation guide
  docs/docsite/rst/installation_guide/intro_installation.rst
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#855 developing_collections_structure.rst: Add EE collection-level metadata link to meta directory subsection
  docs/docsite/rst/dev_guide/developing_collections_structure.rst
Labels: backport-2.15, backport-2.16

#865 Fix Edit on GitHub for templated pages, remove superfluous template, fix broken link
  docs/docsite/.templates/breadcrumbs.html
  docs/docsite/rst/conf.py
  docs/docsite/rst/playbook_guide/playbooks_loops.rst
  docs/templates/modules_by_category.rst.j2
Labels: backport-2.15, backport-2.16

#870 intro_installation: add EE info
  docs/docsite/rst/installation_guide/intro_installation.rst
Labels: backport-2.15, backport-2.16
