Repository ansible/ansible-documentation, pull requests merged in 2023-07, with the labels that each got.

#122 Fix antsibull-docs requirements in docs/docsite/requirements.txt
  docs/docsite/requirements.txt
Labels: backport-2.15

#125 Bump antsibull-docs to 2.3.1
  tests/requirements.txt
Labels: backport-2.15

#134 Add Ansible community 8.2.0 porting guide
  docs/docsite/rst/porting_guides/porting_guide_8.rst
Labels: backport-2.15

#130 update japanese versions
  docs/docsite/sphinx_conf/core_lang_conf.py
Labels: backport-2.15, backport-2.14, backport-2.13

#170 ci labeler: remove `Print event information` step
  .github/workflows/labeler.yml
Labels: backport-2.15, backport-2.14, backport-2.13

#174 Document ansible-core Python support
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: needs_triage

#159 Update playbooks_intro.rst to include dry run option
  docs/docsite/rst/playbook_guide/playbooks_intro.rst
Labels: new_contributor

#188 Fix "Edit on GitHub" links for CLI programs
  docs/docsite/.templates/breadcrumbs.html
  docs/docsite/sphinx_conf/2.10_conf.py
  docs/docsite/sphinx_conf/all_conf.py
  docs/docsite/sphinx_conf/ansible_conf.py
  docs/docsite/sphinx_conf/core_conf.py
  docs/docsite/sphinx_conf/core_lang_conf.py
  docs/templates/cli_rst.j2
  hacking/build_library/build_ansible/command_plugins/generate_man.py
Labels: doc builds, backport-2.15, backport-2.14, backport-2.13

#191 [stable-2.13] Fix misrendered sections in manpage generation
  docs/templates/cli_rst.j2
  hacking/build_library/build_ansible/command_plugins/generate_man.py
  hacking/templates/man.j2
Labels: needs_triage

#190 [stable-2.14] Fix misrendered sections in manpage generation
  docs/templates/cli_rst.j2
  hacking/build_library/build_ansible/command_plugins/generate_man.py
  hacking/templates/man.j2
Labels: needs_triage

#189 [stable-2.15] Fix misrendered sections in manpage generation
  docs/templates/cli_rst.j2
  hacking/build_library/build_ansible/command_plugins/generate_man.py
  hacking/templates/man.j2
Labels: needs_triage

#192 Exclude internal options from man pages and docs
  hacking/build_library/build_ansible/command_plugins/generate_man.py
Labels: doc builds, backport-2.15, backport-2.14, backport-2.13, needs_triage

#202 ci labeler: print PR event information
  .github/workflows/labeler.yml
Labels: needs_triage
