Repository ansible/ansible-documentation, pull requests merged in 2023-08, with the labels that each got.

#201 Fix#129
  docs/docsite/rst/installation_guide/intro_configuration.rst
Labels: new_contributor

#220 Use the new CLI docs generator from ansible-core
  docs/docsite/Makefile
  docs/templates/cli_rst.j2
  hacking/build_library/build_ansible/command_plugins/generate_man.py
Labels: backport-2.15, needs_triage

#221 [stable-2.15] Use the new CLI docs generator from ansible-core (#220)
  docs/docsite/Makefile
  docs/templates/cli_rst.j2
  hacking/build_library/build_ansible/command_plugins/generate_man.py
Labels: doc builds

#141 collection_requirements: add list of accepted licenses
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
Labels: sc_approval

#228 Fix sanity test page titles
  docs/docsite/rst/dev_guide/testing/sanity/no-unicode-literals.rst
  docs/docsite/rst/dev_guide/testing/sanity/release-names.rst
  docs/docsite/rst/dev_guide/testing/sanity/runtime-metadata.rst
Labels: needs_triage

#229 Update the package-data sanity test docs
  docs/docsite/rst/dev_guide/testing/sanity/package-data.rst
Labels: needs_triage

#199 Updated Ansible host file to include two target groups
  examples/hosts
Labels: backport-2.15, backport-2.14, backport-2.13

#186 add pipx instructions to windows_winrm.rst, fix #187
  docs/docsite/rst/os_guide/windows_winrm.rst
Labels: backport-2.15

#237 Use a dedicated version helper for the docs build (#80345)
  docs/docsite/Makefile
  docs/docsite/version_helper.py
Labels: needs_triage

#238 Use a dedicated version helper for the docs build (#80345)
  docs/docsite/Makefile
  docs/docsite/version_helper.py
Labels: needs_triage

#224 [stable-2.14] Use the new CLI docs generator from ansible-core
  docs/docsite/Makefile
  docs/templates/cli_rst.j2
  hacking/build_library/build_ansible/command_plugins/generate_man.py
Labels: doc builds, needs_triage

#225 [stable-2.13] Use the new CLI docs generator from ansible-core
  docs/docsite/Makefile
  docs/templates/cli_rst.j2
  hacking/build_library/build_ansible/command_plugins/generate_man.py
Labels: doc builds, needs_triage

#244 Fix typos in test plugins page
  docs/docsite/rst/plugins/test.rst
Labels: backport-2.15, backport-2.14, backport-2.13

#257 Fix missing newline before a list
  docs/docsite/rst/inventory_guide/intro_inventory.rst
Labels: backport-2.15, backport-2.14, backport-2.13, new_contributor

#262 Use the correct short option for module path
  docs/docsite/rst/command_guide/cheatsheet.rst
Labels: backport-2.15, backport-2.14, backport-2.13

#256 [stable-2.14] pin doc requirements
  docs/docsite/requirements.txt
  docs/docsite/rst/community/documentation_contributions.rst
  tests/constraints.in
  tests/requirements.in
  tests/requirements.txt
Labels: doc builds

#265 Adjust ansible-lint links
  docs/docsite/rst/playbook_guide/playbooks_intro.rst
Labels: backport-2.15, backport-2.14, backport-2.13

#270 [stable-2.13] pin doc requirements
  docs/docsite/rst/community/documentation_contributions.rst
  tests/constraints.in
  tests/requirements.in
  tests/requirements.txt
Labels: doc builds

#274 [stable-2.14] additional dependency cleanup
  docs/docsite/known_good_reqs.txt
  tests/constraints.in
  tests/requirements.in
  tests/requirements.txt
Labels: doc builds

#284 Fix syntax issue before a code block.
  docs/docsite/rst/playbook_guide/playbooks_intro.rst
Labels: backport-2.15, backport-2.14, backport-2.13, needs_triage

#290 Add Ansible community 8.3.0 porting guide
  docs/docsite/rst/porting_guides/porting_guide_8.rst
Labels: backport-2.15

#106 Replace apt-key with signed-by in Debian install instructions
  docs/docsite/rst/installation_guide/installation_distros.rst
Labels: techreview, new_contributor

#297 minor ref fix
  docs/docsite/rst/reference_appendices/python_3_support.rst
Labels: needs_triage

#185 update install guide to inject binaries for argcomplete, fixes #184
  docs/docsite/rst/installation_guide/intro_installation.rst
Labels: backport-2.15

#304 [stable-2.15] getting_started_playbook: improve the doc
  docs/docsite/rst/getting_started/get_started_playbook.rst
  docs/docsite/rst/getting_started/yaml/first_playbook.yaml
Labels: needs_triage

#305 [stable-2.14] getting_started_playbook: improve the doc
  docs/docsite/rst/getting_started/get_started_playbook.rst
  docs/docsite/rst/getting_started/yaml/first_playbook.yaml
Labels: needs_triage

#306 [issues #78]Update collection requirements links
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/communication.rst
  docs/docsite/rst/dev_guide/developing_collections_migrating.rst
  docs/docsite/rst/dev_guide/testing/sanity/import.rst
  docs/docsite/rst/locales/ja/LC_MESSAGES/dev_guide.po
Labels: backport-2.15, backport-2.14, sc_approval

#326 scenario_guides: remove deprecated vultr v1 guide
  docs/docsite/rst/scenario_guides/guide_vultr.rst
  docs/docsite/rst/scenario_guides/guides.rst
Labels: backport-2.15, backport-2.14, backport-2.13

#323 [Stable 2.15] rm unused reqs file #107
  docs/docsite/requirements.txt
Labels: doc builds

#324 [Stable 2.14] rm unused reqs file #107
  docs/docsite/requirements.txt
Labels: doc builds

#325 [Stable 2.13] rm unused reqs file #107
  docs/docsite/requirements.txt
Labels: doc builds

#329 limit sphinx to `< 7.2.0` in requirements-relaxed
  tests/constraints-base.in
Labels: doc builds

#255 Drop docs/docsite/requirements.txt
  docs/docsite/requirements.txt
Labels: doc builds

#280 Add example /usr/bin/env python as Python interpreter
  docs/docsite/rst/reference_appendices/interpreter_discovery.rst
  docs/docsite/rst/reference_appendices/python_3_support.rst
Labels: techreview, new_contributor

#310 Document new retries w/o until
  docs/docsite/rst/playbook_guide/playbooks_loops.rst
Labels: techreview, no_backport

#334 add community day banner
  docs/docsite/.templates/banner.html
Labels: backport-2.15

#320 Bump sphinx to 6.2.1 on devel
  tests/constraints.in
  tests/requirements.txt
Labels: doc builds

#120 development_process.rst: rework Ansibot workflow
  docs/docsite/rst/community/development_process.rst
Labels: backport-2.15, backport-2.14, backport-2.13

#219 Clarify handlers with the same name behavior
  docs/docsite/rst/playbook_guide/playbooks_handlers.rst
Labels: techreview

#288 collection_requirements: ban CLAs in collections
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
Labels: backport-2.15, sc_approval

#281 Update Python requirements for Ansible inclusion requirements document
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: sc_approval
