Repository ansible/ansible-documentation, pull requests merged in 2024-04, with the labels that each got.

#1242 Dependency refresh 2.14
  tests/static.txt
  tests/typing.txt
Labels: dependency_update, tooling

#1243 Dependency refresh 2.15
  tests/static.txt
  tests/typing.txt
Labels: dependency_update, tooling

#1244 Dependency refresh 2.16
  tests/static.txt
  tests/typing.txt
Labels: dependency_update, tooling

#1251 Bump devel tag.py for stable-2.17
  hacking/tagger/tag.py
Labels: no_backport, tooling

#1260 Add Ansible 10.0.0a1 porting guide
  docs/docsite/rst/porting_guides/porting_guide_10.rst
  docs/docsite/rst/porting_guides/porting_guides.rst
Labels: backport-2.17

#1237 [Needs SC vote before merging] Steering Committee: team membership
  docs/docsite/rst/community/steering/community_steering_committee.rst
  docs/docsite/rst/community/steering/steering_committee_membership.rst
Labels: sc_approval

#1265 [Stable 2.16] Manual backport of dep refresh
  tests/formatters.txt
  tests/static.txt
  tests/typing.txt
Labels: dependency_update, tooling

#1267 [Stable 2.14] Manual backport of dep refresh
  tests/formatters.txt
  tests/static.txt
  tests/typing.txt
Labels: dependency_update, tooling

#1270 community_topics_workflow: fix formatting
  docs/docsite/rst/community/steering/community_topics_workflow.rst
Labels: sc_approval, backport-2.17

#1274 ansible-core 2.17 porting guide: remote Python version support
  docs/docsite/rst/porting_guides/porting_guide_core_2.17.rst
Labels: backport-2.17

#1233 Update developing_modules_general.rst
  docs/docsite/rst/dev_guide/developing_modules_general.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17

#1190 Update playbooks_blocks.rst
  docs/docsite/rst/playbook_guide/playbooks_blocks.rst
Labels: new_contributor

#1176 Build package docs
  .github/workflows/build-package-docs.yaml
Labels: doc builds

#1310 add the backport-2.17 label
  .github/workflows/pip-compile-dev.yml
Labels: tooling

#1312 Add Ansible community 9.5.1 porting guide
  docs/docsite/rst/porting_guides/porting_guide_9.rst
Labels: backport-2.16, backport-2.17

#1316 [Stable-2.17] Bump wntrblm/nox from 2024.03.02 to 2024.04.15
  .github/workflows/reusable-nox.yml
  .github/workflows/reusable-pip-compile.yml
Labels: tooling

#1317 [Stable-2.16] Bump wntrblm/nox from 2024.03.02 to 2024.04.15
  .github/workflows/reusable-nox.yml
  .github/workflows/reusable-pip-compile.yml
Labels: tooling

#1318 [Stable-2.15] Bump wntrblm/nox from 2024.03.02 to 2024.04.15
  .github/workflows/reusable-nox.yml
Labels: tooling

#1319 [Stable-2.14] Bump wntrblm/nox from 2024.03.02 to 2024.04.15
  .github/workflows/reusable-nox.yml
Labels: tooling

#1293 MUNI tech writers: typo fix (#1199)
  docs/docsite/rst/roadmap/ROADMAP_2_7.rst
Labels: backport-2.15, backport-2.14, backport-2.13, backport-2.16, MUNI tech writers, backport-2.17

#1275 Update playbooks_reuse_roles.rst
  docs/docsite/rst/playbook_guide/playbooks_reuse_roles.rst
Labels: backport-2.15, backport-2.14, backport-2.16, backport-2.17

#1258 MUNI_TECH_WRITERS: Paramiko contradictions, issue #1042
  docs/docsite/rst/dev_guide/developing_plugins.rst
  docs/docsite/rst/inventory_guide/intro_inventory.rst
  docs/docsite/rst/reference_appendices/glossary.rst
Labels: backport-2.15, backport-2.14, new_contributor, backport-2.16, MUNI tech writers, backport-2.17

#1309 Fixes name of the upload artifact
  .github/workflows/build-package-docs.yaml
Labels: doc builds, tooling

#1283 MUNI_TECH_WRITERS: Clarify example module group name in the playbook guide
  docs/docsite/rst/playbook_guide/playbooks_module_defaults.rst
Labels: backport-2.15, backport-2.14, new_contributor, backport-2.16, MUNI tech writers, backport-2.17

#1303 MUNI tech writers: absolute path referencing mentioned (#96)
  docs/docsite/rst/tips_tricks/ansible_tips_tricks.rst
Labels: backport-2.15, backport-2.14, backport-2.16, MUNI tech writers, backport-2.17

#1296 MUNI tech writers: Mention ANSIBLE_CONNECTION_PATH option on Connection plugins page (#793)
  docs/docsite/rst/plugins/connection.rst
Labels: backport-2.15, backport-2.14, backport-2.16, MUNI tech writers, backport-2.17

#1311 Defining changed (issue #1167)
  docs/docsite/rst/playbook_guide/playbooks_error_handling.rst
  docs/docsite/rst/playbook_guide/playbooks_handlers.rst
Labels: backport-2.15, backport-2.14, new_contributor, backport-2.16, MUNI tech writers, backport-2.17

#1347 Add examples to clarify inventory plugin usage
  docs/docsite/rst/plugins/inventory.rst
Labels: new_contributor, backport-2.17

#1358 improve workflow syntax
  .github/workflows/build-package-docs.yaml
Labels: doc builds, tooling

#1348 update symlink step syntax in docs build workflow
  .github/workflows/build-package-docs.yaml
Labels: doc builds, tooling

#1378 Add Ansible 10.0.0a2 porting guide
  docs/docsite/rst/porting_guides/porting_guide_10.rst
Labels: backport-2.17

#1315 MUNI_TECH_WRITERS: Better documented local collections for playbooks #1129
  docs/docsite/rst/collections_guide/collections_installing.rst
  docs/docsite/rst/shared_snippets/installing_collections.txt
Labels: backport-2.15, backport-2.14, new_contributor, backport-2.16, MUNI tech writers, backport-2.17
