Repository ansible/ansible-documentation, pull requests merged in 2024-05, with the labels that each got.

#1368 Fix typos in style guide
  docs/docsite/rst/dev_guide/style_guide/index.rst
Labels: backport-2.15, new_contributor, backport-2.16, MUNI tech writers, backport-2.17

#1364 CONTRIBUTING: document backport labels and PR Merging
  CONTRIBUTING.md
Labels: backport-2.15, backport-2.14, backport-2.16, backport-2.17

#1340 Remove additional references to smart connections
  examples/scripts/uptime.py
Labels: backport-2.15, backport-2.14, backport-2.16, backport-2.17

#1302 Integrate ansible-creator and devtools into the developing collections guide
  docs/docsite/rst/dev_guide/developing_collections_creating.rst
Labels: backport-2.15, backport-2.14, new_contributor, backport-2.16, MUNI tech writers, backport-2.17

#1366 update codespell ignore lines
  .codespellignorelines
Labels: backport-2.15, backport-2.14, backport-2.16, tooling, backport-2.17

#1367 Adding explanation for combining until with loop
  docs/docsite/rst/playbook_guide/playbooks_loops.rst
Labels: backport-2.15, backport-2.14, new_contributor, backport-2.16, backport-2.17

#1417 Bump antsibull-docs to 2.11.0
  tests/constraints.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: backport-2.15, backport-2.16, backport-2.17

#1420 intro_installation.rst: "shells" -> "shell's" to make possessive
  docs/docsite/rst/installation_guide/intro_installation.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17

#1419 [stable-2.16] Bump antsibull-docs to 2.11.0. (#1417)
  tests/constraints.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: backport-2.15

#1410 how_can_i_help page: rephrase the paragraph mentioning forums
  docs/docsite/rst/community/how_can_I_help.rst
Labels: backport-2.15, backport-2.14, backport-2.16, backport-2.17

#1400 Restore the umask note for building docs
  docs/docsite/rst/community/documentation_contributions.rst
Labels: backport-2.15, backport-2.14, backport-2.16, backport-2.17

#1391 clarify backup_file
  docs/docsite/rst/reference_appendices/common_return_values.rst
  docs/docsite/rst/reference_appendices/faq.rst
Labels: backport-2.15, backport-2.14, backport-2.16, backport-2.17

#1320 Document the possibility of vars/main and defaults/main being directories
  docs/docsite/rst/playbook_guide/playbooks_filters.rst
  docs/docsite/rst/playbook_guide/playbooks_reuse_roles.rst
  docs/docsite/rst/playbook_guide/playbooks_variables.rst
Labels: backport-2.15, backport-2.14, new_contributor, backport-2.16, MUNI tech writers, backport-2.17

#1256 [Needs SC vote before merging] SC: update collection inclusion procedure
  docs/docsite/rst/community/steering/community_steering_committee.rst
Labels: sc_approval

#1375 [Stable-2.16] ci: refresh dev dependencies
  tests/formatters.txt
  tests/static.txt
  tests/typing.txt
Labels: dependency_update, tooling

#1376 [Stable-2.15] ci: refresh dev dependencies
  tests/formatters.txt
  tests/static.txt
  tests/typing.txt
Labels: dependency_update, tooling

#1377 [Stable-2.14] ci: refresh dev dependencies
  tests/formatters.txt
  tests/static.txt
  tests/typing.txt
Labels: dependency_update, tooling

#1452 Add Ansible 10.0.0a3 porting guide
  docs/docsite/rst/porting_guides/porting_guide_10.rst
Labels: backport-2.17

#1426 Update release table for 2.17
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.17, core_approval

#1451 Update community topics links
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/communication.rst
  docs/docsite/rst/community/contributor_path.rst
  docs/docsite/rst/community/maintainers_guidelines.rst
  docs/docsite/rst/community/steering/community_steering_committee.rst
  docs/docsite/rst/community/steering/community_topics_workflow.rst
  docs/docsite/rst/community/steering/steering_committee_membership.rst
  docs/docsite/rst/community/steering/steering_committee_past_members.rst
  docs/docsite/rst/community/steering/steering_index.rst
Labels: sc_approval

#1463 [stable-2.17] set correct version for 2.17 release
  docs/docsite/rst/conf.py
Labels: no_backport

#1458 Remove depreciated platforms reference
  docs/docsite/rst/galaxy/user_guide.rst
Labels: backport-2.17

#1248 Cheatsheet entry for the ansible-doc command
  docs/docsite/rst/command_guide/cheatsheet.rst
Labels: backport-2.15, backport-2.16, backport-2.17

#1416 MUNI Tech Writers: Timeout with retry in loops documentation
  docs/docsite/rst/playbook_guide/playbooks_loops.rst
Labels: backport-2.15, backport-2.14, new_contributor, backport-2.16, MUNI tech writers, backport-2.17

#1479 Semantic markup: fix list
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
Labels: backport-2.15, backport-2.16, backport-2.17

#1421 collection_requirements: update community topic links
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/communication.rst
Labels: backport-2.15, sc_approval, backport-2.16, backport-2.17

#1464 update version switcher to support 2.17
  docs/docsite/rst/conf.py
Labels: backport-2.15, backport-2.16, backport-2.17

#1493 Add Ansible community 9.6.0 porting guide
  docs/docsite/rst/porting_guides/porting_guide_9.rst
Labels: backport-2.16, backport-2.17

#1505 Update collection_checklist.md links to point to new location
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/steering/community_steering_committee.rst
Labels: sc_approval

#1510 [stable-2.15] Move Ansible package collection removal process to docs.ansible.com (…
  docs/docsite/rst/community/collection_contributors/collection_package_removal.rst
  docs/docsite/rst/community/steering/community_steering_committee.rst
  docs/docsite/rst/conf.py
Labels: sc_approval

#1508 [stable-2.17] Move Ansible package collection removal process to docs.ansible.com (…
  docs/docsite/rst/community/collection_contributors/collection_package_removal.rst
  docs/docsite/rst/community/steering/community_steering_committee.rst
  docs/docsite/rst/conf.py
Labels: sc_approval

#1321 Muni tech writers: Ansible include_task search documentation incorrect #357
  docs/docsite/rst/playbook_guide/playbook_pathing.rst
Labels: backport-2.15, backport-2.14, backport-2.16, MUNI tech writers, backport-2.17

#1504 update backport instructions for 2.17
  docs/docsite/rst/community/development_process.rst
Labels: backport-2.15, backport-2.16, backport-2.17

#1503 [stable-2.14] EOL 2.14 docs
  docs/docsite/rst/conf.py
Labels: no_backport

#1502 mark 2.14 EOL in the release table
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.15, backport-2.14, backport-2.16, backport-2.17

#1460 Add tagger section to README per 1272
  README.md
Labels: new_contributor, no_backport, tooling

#1500 [backport stable-2.15] ci: refresh dev dependencies
  tests/formatters.txt
  tests/typing.txt
Labels: dependency_update, tooling

#1501 [backport stable-2.14] ci: refresh dev dependencies
  tests/formatters.txt
  tests/typing.txt
Labels: dependency_update, tooling

#1522 release_and_maintenance: mark 8.x unmaintained as 8.7.0 released
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17

#1530 fix minor typo in Makefile
  docs/docsite/Makefile
Labels: backport-2.15, backport-2.14, backport-2.16, tooling, backport-2.17

#1529 Requesting a collection: replace overview links
  docs/docsite/rst/community/communication.rst
  docs/docsite/rst/dev_guide/developing_collections.rst
  docs/docsite/rst/dev_guide/developing_collections_creating.rst
  docs/docsite/rst/dev_guide/developing_collections_path.rst
Labels: backport-2.15, backport-2.16, backport-2.17

#1459 Python collection requirements: restructure
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
Labels: sc_approval
