Repository ansible/ansible-documentation, pull requests merged in 2024-01, with the labels that each got.

#987 Document collection naming
  docs/docsite/rst/dev_guide/developing_collections_creating.rst
Labels: backport-2.15, backport-2.16

#930 Adds note for more details about variable precedence
  docs/docsite/rst/inventory_guide/intro_inventory.rst
Labels: backport-2.16

#1005 docs: Fixed Developer Certificate Of Origin link
  docs/docsite/rst/community/developer_certificate_of_origin.rst
Labels: backport-2.16

#984 docs: Document removal of ConfigureRemotingForAnsible.ps1 #794
  docs/docsite/rst/os_guide/windows_setup.rst
  examples/README.md
  examples/scripts/README.md
Labels: backport-2.16

#922 convert core docs to use Ansible sphinx theme
  docs/docsite/_static/.keep
  docs/docsite/_static/css/core-color-scheme.css
  docs/docsite/rst/conf.py
Labels: backport-2.15, backport-2.16

#990 pr_labeler: refactor new_contributor_welcome code
  hacking/pr_labeler/label.py
Labels: backport-2.15, backport-2.14, backport-2.16, tooling, pr_labeler

#1029 Update task definition in playbook getting started doc
  docs/docsite/rst/getting_started/get_started_playbook.rst
Labels: backport-2.16

#1027 Update Arch Linux bugtracker link
  docs/docsite/rst/installation_guide/installation_distros.rst
Labels: backport-2.16

#880 fix intersphinx tuples
  docs/docsite/jinja2.inv
  docs/docsite/python2.inv
  docs/docsite/python3.inv
  docs/docsite/rst/conf.py
Labels: backport-2.16

#912 Add how to request a working group
  docs/docsite/rst/community/communication.rst
Labels: backport-2.16

#1003 added `gather_facts/(yes/no)`
  docs/docsite/rst/dev_guide/testing/sanity/integration-aliases.rst
Labels: backport-2.16

#995 collection requirements/steering committee inclusion policy: change
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/steering/community_steering_committee.rst
Labels: sc_approval

#871 collection_requirements: add meta/execution-environments.yml
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
Labels: sc_approval, backport-2.16

#1055 nox: run clone-core session in a venv as well
  noxfile.py
Labels: backport-2.15, backport-2.14, backport-2.16, tooling

#740 ci: avoid interpolating inputs into run: scripts
  .github/workflows/labeler.yml
  .github/workflows/reusable-pip-compile.yml
Labels: no_backport, tooling

#1064 ci: fix reusable-pip-compile workflow quoting
  .github/workflows/reusable-pip-compile.yml
Labels: no_backport, tooling

#1051 Add network differences explanation
  docs/docsite/rst/network/getting_started/network_differences.rst
Labels: techreview

#1061 [stable-2.16] ci: refresh dev dependencies
  tests/static.txt
  tests/typing.txt
Labels: backport-2.15, backport-2.14, dependency_update, tooling

#1066 ci pip-compile: add appropriate labels to dev and docs jobs
  .github/workflows/pip-compile-dev.yml
  .github/workflows/pip-compile-docs.yml
  .github/workflows/reusable-pip-compile.yml
Labels: no_backport, tooling, merge_commit

#997 community_steering_committee.rst: update with respect to forum and collection requirements
  docs/docsite/rst/community/steering/community_steering_committee.rst
Labels: backport-2.15, sc_approval, backport-2.16

#1090 Bump antsibull-docs to 2.7.0
  tests/constraints.in
  tests/requirements-relaxed.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: backport-2.15, backport-2.14, backport-2.13, backport-2.16

#1087 Add Ansible community 9.2.0 porting guide
  docs/docsite/rst/porting_guides/porting_guide_9.rst
Labels: backport-2.16

#994 Ansible 10 roadmap
  docs/docsite/rst/roadmap/COLLECTIONS_10.rst
  docs/docsite/rst/roadmap/ansible_roadmap_index.rst
Labels: sc_approval
