Repository ansible/ansible-documentation, pull requests merged in 2024-12, with the labels that each got.

#2228 Add package to getting started ee
  docs/docsite/rst/getting_started_ee/setup_environment.rst
Labels: new_contributor, backport-2.16, backport-2.17, backport-2.18

#2241 Add porting guide for Ansible 11.1.0
  docs/docsite/rst/porting_guides/porting_guide_11.rst
Labels: backport-2.18

#2242 Add porting guide for Ansible 10.7.0
  docs/docsite/rst/porting_guides/porting_guide_10.rst
Labels: backport-2.17, backport-2.18

#2138 Add 2.19 roadmap
  .codespellignorelines
  docs/docsite/rst/roadmap/ROADMAP_2_19.rst
  docs/docsite/rst/roadmap/ansible_core_roadmap_index.rst
Labels: no_backport

#2253 run_execution_environment.rst: fix a note
  docs/docsite/rst/getting_started_ee/run_execution_environment.rst
Labels: backport-2.16, backport-2.17, backport-2.18

#2148 add maintainer docs for building and publishing
  MAINTAINERS.md
Labels: no_backport, tooling

#2238 ansible-vault show how to decrypt strings
  docs/docsite/rst/vault_guide/vault_encrypting_content.rst
Labels: backport-2.16, backport-2.17, backport-2.18

#2239 Add flymake-ansible-lint.el to list of tools
  docs/docsite/rst/community/other_tools_and_programs.rst
Labels: new_contributor, backport-2.16, backport-2.17, backport-2.18

#2240 fix file name to execution-environment.yml
  docs/docsite/rst/dev_guide/developing_collections_structure.rst
Labels: backport-2.16, backport-2.17, backport-2.18

#2261 [stable-2.17] Update noxfile to fix failing workflows
  noxfile.py
Labels: tooling

#2263 [stable-2.16] Update noxfile to fix failing workflows
  noxfile.py
Labels: tooling

#2265 [stable-2.14] Update noxfile to fix failing workflows
  noxfile.py
Labels: tooling

#2258 Link to templating functions from the variables page
  docs/docsite/rst/playbook_guide/playbooks_lookups.rst
  docs/docsite/rst/playbook_guide/playbooks_variables.rst
Labels: backport-2.16, backport-2.17, backport-2.18

#2259 use name instead of source for installing collection dir requirements
  docs/docsite/rst/shared_snippets/installing_collections_file.rst
Labels: backport-2.16, backport-2.17, backport-2.18

#2262 [stable-2.18] Update noxfile to fix failing workflows
  noxfile.py
Labels: tooling

#2260 Update noxfile and pip-compile sessions to fix failing workflows
  .github/workflows/pip-compile-dev.yml
  .github/workflows/pip-compile-docs.yml
  noxfile.py
Labels: no_backport, tooling

#2293 fix typo
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
Labels: sc_approval, new_contributor

#2304 ci pip-compile: specify the correct Python version for each branch
  .github/workflows/pip-compile-dev.yml
  .github/workflows/pip-compile-docs.yml
  .github/workflows/reusable-pip-compile.yml
Labels: no_backport, tooling

#2252 Ansible 12 roadmap
  docs/docsite/rst/roadmap/COLLECTIONS_12.rst
  docs/docsite/rst/roadmap/ansible_roadmap_index.rst
Labels: sc_approval

#2284 [Needs SC review] community/other_tools_and_programs.rst: update
  .github/CODEOWNERS
  docs/docsite/rst/community/other_tools_and_programs.rst
Labels: backport-2.16, backport-2.17, backport-2.18
