Repository ansible/ansible-documentation, pull requests merged in 2024-07, with the labels that each got.

#1422 [WIP, needs vote before merging] collection_requirements.rst: update
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/steering/community_steering_committee.rst
Labels: sc_approval

#1650 Output workflow parameters for approval details
  .github/workflows/build-package-docs.yaml
Labels: no_backport, tooling

#1671 [stable-2.17] ci: refresh dev dependencies
  tests/static.txt
  tests/typing.txt
Labels: dependency_update, tooling

#1672 [stable-2.16] ci: refresh dev dependencies
  tests/static.txt
  tests/typing.txt
Labels: dependency_update, tooling

#1673 [stable-2.15] ci: refresh dev dependencies
  tests/static.txt
  tests/typing.txt
Labels: dependency_update, tooling

#1674 [stable-2.14] ci: refresh dev dependencies
  tests/static.txt
  tests/typing.txt
Labels: dependency_update, tooling

#1665 [stable-2.16] [WIP, needs vote before merging] collection_requirements.rst: update …
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/steering/community_steering_committee.rst
Labels: sc_approval

#1666 [stable-2.15] [WIP, needs vote before merging] collection_requirements.rst: update …
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/steering/community_steering_committee.rst
Labels: sc_approval

#1663 Nightly builds for package docs publishing workflow
  .github/workflows/build-package-docs.yaml
Labels: doc builds, tooling

#1659 Adding daily schedule to CI build
  .github/workflows/ci.yaml
Labels: no_backport, tooling

#1683 remove the schedule from the workflow dispatch job
  .github/workflows/build-package-docs.yaml
Labels: doc builds, tooling

#1651 notify docs matrix channel on docs build failures
  .github/workflows/build-package-docs.yaml
Labels: no_backport, tooling

#1684 collection_requirements: fix typo
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
Labels: backport-2.15, sc_approval, backport-2.16, backport-2.17

#1692 restore anchor in communication guide
  docs/docsite/rst/community/communication.rst
Labels: backport-2.15, backport-2.16, backport-2.17

#1697 Add porting guide for Ansible 10.2.0
  docs/docsite/rst/porting_guides/porting_guide_10.rst
Labels: backport-2.17

#1698 Add porting guide for Ansible 9.8.0
  docs/docsite/rst/porting_guides/porting_guide_9.rst
Labels: backport-2.16, backport-2.17

#1028 Move community_topics_workflow to docs.ansible.com
  docs/docsite/rst/community/communication.rst
  docs/docsite/rst/community/steering/community_topics_workflow.rst
Labels: sc_approval

#1649 Issue #1633 nox session for tagging
  .github/workflows/pip-compile-dev.yml
  README.md
  noxfile.py
  tests/tag.in
  tests/tag.txt
  tests/typing.in
Labels: no_backport, tooling

#1709 Be more explicit about registering with a loop
  docs/docsite/rst/playbook_guide/playbooks_loops.rst
Labels: techreview, backport-2.15, new_contributor, backport-2.16, backport-2.17

#1696 add vault password file example
  docs/docsite/rst/vault_guide/vault_managing_passwords.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17

#1712 [backport stable-2.16] ci: refresh dev dependencies (#1707)
  tests/static.txt
  tests/typing.txt
Labels: dependency_update, tooling

#1714 [backport stable-2.14] ci: refresh dev dependencies (#1707)
  tests/static.txt
  tests/typing.txt
Labels: dependency_update, tooling
