Repository ansible/ansible-documentation, pull requests merged in 2024-03, with the labels that each got.

#1075 [SC vote needed] Steering Committee: simplify member removal policy; update links
  docs/docsite/rst/community/steering/steering_committee_membership.rst
Labels: sc_approval

#1182 Data Tagging Delayed to 2.18
  docs/docsite/rst/roadmap/ROADMAP_2_17.rst
Labels: backport-2.16

#1175 Fix typo
  docs/docsite/rst/getting_started/get_started_playbook.rst
Labels: new_contributor, backport-2.16

#1180 Clarify documentation about empty collections vs collection skeletons
  docs/docsite/rst/dev_guide/developing_collections_creating.rst
Labels: no_backport

#1181 Update documentation about `vars:` in `roles:` for 2.15+
  docs/docsite/rst/playbook_guide/playbooks_reuse_roles.rst
Labels: backport-2.16

#1191 use ruff check <path> syntax in noxfile
  noxfile.py
Labels: backport-2.15, backport-2.14, backport-2.16, tooling

#1179 [Stable 2.14] Bump wntrblm/nox from 2023.04.22 to 2024.03.02
  .github/workflows/reusable-nox.yml
Labels: tooling

#1201 add back suggested edit from #1175
  docs/docsite/rst/getting_started/get_started_playbook.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#1188 Trim down the docs banners
  docs/docsite/.templates/banner.html
  docs/docsite/rst/conf.py
Labels: backport-2.16

#1198 Add link to antsibull-docs docsite
  docs/docsite/rst/dev_guide/developing_collections_documenting.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#1084 Add script to create git tags for new core releases
  hacking/tagger/requirements.txt
  hacking/tagger/tag.py
  noxfile.py
  tests/typing.in
  tests/typing.txt
Labels: no_backport, tooling

#1210 Update testing_units_modules.rst
  docs/docsite/rst/dev_guide/testing_units_modules.rst
Labels: new_contributor, backport-2.16

#1209 Unintended or undocumented functionality may be removed without deprecation
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.16

#1208 Update playbooks_advanced_syntax.rst
  docs/docsite/rst/playbook_guide/playbooks_advanced_syntax.rst
Labels: new_contributor, backport-2.16

#1171 Cheat sheet instructions for ansible ad-hoc commands
  docs/docsite/rst/command_guide/cheatsheet.rst
Labels: backport-2.16

#1130 Document attributes
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
  docs/docsite/rst/playbook_guide/playbooks_reuse_roles.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#1238 Add Ansible 9.4.0 porting guide
  docs/docsite/rst/porting_guides/porting_guide_9.rst
Labels: backport-2.16
