Repository ansible/ansible-documentation, pull requests merged in 2024-08, with the labels that each got.

#1731 Update integration test guide docker flag usage
  docs/docsite/rst/dev_guide/testing_integration.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17

#1740 Added 'direct' to general precedence
  docs/docsite/rst/reference_appendices/general_precedence.rst
Labels: backport-2.15, backport-2.16, backport-2.17

#1747 Fix CI in devel
  docs/bin/clone-core.py
  tests/checkers/docs-build.py
Labels: no_backport

#1746 Add porting guide for Ansible 10.3.0
  docs/docsite/rst/porting_guides/porting_guide_10.rst
Labels: backport-2.17

#1703 [Needs SC vote before merging] Collection requirements: add Forum-related reqs
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/communication.rst
Labels: sc_approval

#1763 [stable-2.15] Collection requirements: add Forum-related reqs (#1703)
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/communication.rst
Labels: sc_approval

#1616 dev pip-compile: switch devel branch pip-compile to 3.11
  .github/workflows/pip-compile-dev.yml
  .github/workflows/pip-compile-docs.yml
  .github/workflows/reusable-pip-compile.yml
  noxfile.py
Labels: no_backport, tooling

#1718 add note about arguments in shebang in modules
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
  docs/docsite/rst/reference_appendices/faq.rst
Labels: new_contributor

#1756 ci: ensure ansible-core files exist before running docs build
  docs/bin/clone-core.py
  noxfile.py
Labels: backport-2.15, backport-2.14, backport-2.16, tooling, backport-2.17

#1729 Ansible 11 roadmap
  docs/docsite/rst/roadmap/COLLECTIONS_11.rst
  docs/docsite/rst/roadmap/ansible_roadmap_index.rst
Labels: sc_approval

#1776 fix yaml indents network documents
  docs/docsite/rst/network/getting_started/network_connection_options.rst
  docs/docsite/rst/network/user_guide/platform_nxos.rst
Labels: backport-2.15, backport-2.16, backport-2.17

#1785 Fix links in collection requirements
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
Labels: backport-2.15, sc_approval, backport-2.16, backport-2.17

#1798 Fix broken list markup in the "Installing collections" documentation.
  docs/docsite/rst/collections_guide/collections_installing.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17

#1799 Bump antsibull-docs and antsibull-docs-parser versions
  tests/constraints.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: backport-2.16, backport-2.17

#1788 [stable-2.17] tests: update pydantic version in lockfile
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: doc builds, no_backport

#1789 [stable-2.16] tests: update pydantic version in lockfile
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: doc builds, no_backport

#1790 [stable-2.15] tests: update dependencies for compatibility with new Pythons
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: doc builds, no_backport

#1791 [stable-2.14] tests: update dependencies for compatibility with new Pythons
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: doc builds, no_backport

#1757 nox: support nox uv backend
  noxfile.py
Labels: backport-2.15, backport-2.14, backport-2.16, tooling, backport-2.17

#1805 steering_committee_membership: fix rst link syntax error
  docs/docsite/rst/community/steering/steering_committee_membership.rst
Labels: backport-2.15, sc_approval, backport-2.16, backport-2.17

#1815 Clarify any_errors_fatal behavior change in 2.17 porting guide
  docs/docsite/rst/porting_guides/porting_guide_core_2.17.rst
Labels: backport-2.17

#1806 steering_committee_membership: clarify guidelines about team represen…
  docs/docsite/rst/community/steering/steering_committee_membership.rst
Labels: sc_approval, backport-2.17

#1819 [stable-2.15] steering_committee_membership: clarify guidelines about team represen…
  docs/docsite/rst/community/steering/steering_committee_membership.rst
Labels: sc_approval

#1818 [stable-2.16] steering_committee_membership: clarify guidelines about team represen…
  docs/docsite/rst/community/steering/steering_committee_membership.rst
Labels: sc_approval
