Repository ansible/ansible-documentation, pull requests merged in 2024-10, with the labels that each got.

#1960 add a missing word in introduction
  docs/docsite/rst/getting_started/introduction.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17, backport-2.18

#1961 Moved when condition after task name for block example
  docs/docsite/rst/playbook_guide/playbooks_blocks.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17, backport-2.18

#1970 Remove no longer applicable part
  docs/docsite/rst/dev_guide/developing_collections_migrating.rst
Labels: backport-2.16, backport-2.17, backport-2.18

#1975 ee getting started missing content
  docs/docsite/rst/getting_started_ee/build_execution_environment.rst
Labels: backport-2.16, backport-2.17, backport-2.18

#1982 Update playbooks_error_handling.rst
  docs/docsite/rst/playbook_guide/playbooks_error_handling.rst
Labels: backport-2.15, backport-2.16, backport-2.17, backport-2.18

#1988 Add porting guide for Ansible 9.11.0
  docs/docsite/rst/porting_guides/porting_guide_9.rst
Labels: backport-2.16, backport-2.17, backport-2.18

#1987 Add porting guide for Ansible 10.5.0
  docs/docsite/rst/porting_guides/porting_guide_10.rst
Labels: backport-2.17, backport-2.18

#1994 Upgrade antsibull-docs to 2.15.0 and antsibull-core to 3.3.0
  tests/constraints.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: backport-2.16, backport-2.17, backport-2.18

#1996 update docs team info page
  hacking/pr_labeler/pr_labeler/data/docs_team_info.md
Labels: backport-2.16, tooling, backport-2.17, backport-2.18

#2000 Matrix not matrix
  MAINTAINERS.md
  hacking/pr_labeler/pr_labeler/data/docs_team_info.md
Labels: no_backport, tooling

#2014 Add porting guide for Ansible 11.0.0a2
  docs/docsite/rst/porting_guides/porting_guide_11.rst
Labels: backport-2.18

#2001 Update docs build to support the new antsibull-docs 2.15.0 features
  hacking/build_library/build_ansible/command_plugins/docs_build.py
Labels: backport-2.16, backport-2.17, backport-2.18

#1950 Pip compile check mode
  .github/workflows/pip-compile-dev.yml
  .github/workflows/pip-compile-docs.yml
  .github/workflows/reusable-nox.yml
  noxfile.py
Labels: no_backport, tooling, merge_commit

#1948 [stable-2.16] support pip-compile check mode and remove pip-compile workflows from stable branch
  .github/workflows/pip-compile-dev.yml
  .github/workflows/pip-compile-docs.yml
  .github/workflows/reusable-nox.yml
  .github/workflows/reusable-pip-compile.yml
  noxfile.py
Labels: no_backport, tooling, merge_commit

#1949 [stable-2.15] nox pip-compile: support check mode
  .github/workflows/reusable-nox.yml
  noxfile.py
Labels: no_backport, tooling

#1939 Remove unsupported API example
  docs/docsite/rst/dev_guide/developing_api.rst
  examples/scripts/uptime.py
Labels: backport-2.18

#1900 Tagging nuance
  docs/docsite/rst/playbook_guide/playbooks_handlers.rst
  docs/docsite/rst/playbook_guide/playbooks_tags.rst
Labels: backport-2.15, backport-2.14, backport-2.13, backport-2.16, backport-2.17

#2005 use standard indentation
  docs/docsite/rst/playbook_guide/playbooks_variables.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17, backport-2.18

#2004 docs typo, missing a space
  docs/docsite/rst/getting_started/yaml/first_playbook.yaml
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17, backport-2.18

#2036 fix network_best_practices_2.5.rst docs
  docs/docsite/rst/network/user_guide/network_best_practices_2.5.rst
Labels: backport-2.15, backport-2.16, backport-2.17, backport-2.18

#2041 [stable-2.18] Bump wntrblm/nox from 2024.04.15 to 2024.10.09 (#2006)
  .github/workflows/build-package-docs.yaml
  .github/workflows/reusable-nox.yml
Labels: tooling

#2042 [stable-2.17] Bump wntrblm/nox from 2024.04.15 to 2024.10.09 (#2006)
  .github/workflows/reusable-nox.yml
Labels: tooling

#2044 [stable-2.15] Bump wntrblm/nox from 2024.04.15 to 2024.10.09 (#2006)
  .github/workflows/reusable-nox.yml
Labels: tooling

#2032 remove build workflow from stable
  .github/workflows/build-package-docs.yaml
Labels: tooling

#2033 update maintainers guide to git rm build workflow
  MAINTAINERS.md
Labels: tooling

#1971 Add rules on moving content to collections outside of Ansible
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
Labels: sc_approval

#597 Add details of interactions between notifications and loops
  docs/docsite/rst/playbook_guide/playbooks_handlers.rst
Labels: backport-2.15, backport-2.14, new_contributor, backport-2.16, backport-2.17, backport-2.18

#2062 fix: correct typos
  docs/docsite/rst/porting_guides/porting_guide_5.rst
  docs/docsite/rst/porting_guides/porting_guide_core_2.12.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17, backport-2.18

#1893 Update module default groups documentation
  docs/docsite/rst/playbook_guide/playbooks_module_defaults.rst
Labels: backport-2.16, backport-2.17, backport-2.18

#2085 nox pip-compile: temporarily pin pip version
  noxfile.py
Labels: backport-2.16, tooling, backport-2.17, backport-2.18

#2076 Added 2.18 porting guide
  docs/docsite/rst/porting_guides/core_porting_guides.rst
  docs/docsite/rst/porting_guides/porting_guide_core_2.18.rst
Labels: backport-2.18
