Repository ansible/ansible-documentation, pull requests merged in 2024-06, with the labels that each got.

#1546 Update playbooks_blocks.rst
  docs/docsite/rst/playbook_guide/playbooks_blocks.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17

#1551 [2.17] update to version 10
  docs/docsite/rst/conf.py
Labels: no_backport

#1555 Add Ansible community 10.0.0 porting guide
  docs/docsite/rst/porting_guides/porting_guide_10.rst
Labels: backport-2.17

#1543 Update release table for Ansible 10 and 9
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.16, backport-2.17

#1523 Porting Guide 2.17.0 adding assert details
  docs/docsite/rst/porting_guides/porting_guide_core_2.17.rst
Labels: documentation, backport-2.17, core_approval

#1562 Update playbooks_advanced_syntax.rst
  docs/docsite/rst/playbook_guide/playbooks_advanced_syntax.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17

#1570 Update the Ansible 10 porting guide
  docs/docsite/rst/porting_guides/porting_guide_10.rst
Labels: backport-2.17

#1566 Add Ansible 10 to intersphinx links
  docs/docsite/rst/conf.py
Labels: backport-2.16, backport-2.17

#1568 remove mailchimp subscribe from docs
  docs/docsite/rst/community/communication.rst
Labels: backport-2.15, backport-2.16, backport-2.17

#1569 Update playbooks_loops.rst
  docs/docsite/rst/playbook_guide/playbooks_loops.rst
Labels: new_contributor, backport-2.16, backport-2.17

#1524 Update uptime.py
  examples/scripts/uptime.py
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17

#1567 cause people keep doing this
  docs/docsite/rst/inventory_guide/intro_inventory.rst
Labels: backport-2.15, backport-2.16, backport-2.17

#1587 Fix up PowerShell and Windows support lifecycle
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17

#1589 clarify how to verify collection-level docs
  docs/docsite/rst/community/documentation_contributions.rst
  docs/docsite/rst/dev_guide/developing_collections_documenting.rst
Labels: backport-2.15, backport-2.16, backport-2.17

#1602 [backport stable-2.16] ci: refresh dev dependencies
  tests/formatters.txt
  tests/static.txt
  tests/typing.txt
Labels: tooling

#1603 [backport stable-2.15] ci: refresh dev dependencies
  tests/formatters.txt
  tests/static.txt
  tests/typing.txt
Labels: tooling

#1604 [backport stable-2.14] ci: refresh dev dependencies
  tests/formatters.txt
  tests/static.txt
  tests/typing.txt
Labels: tooling

#1600 use the package version as the branch name
  .github/workflows/build-package-docs.yaml
Labels: tooling

#1609 Add porting guide for 9.7.0
  docs/docsite/rst/porting_guides/porting_guide_9.rst
Labels: backport-2.16, backport-2.17

#1610 Add porting guide for Ansible 10.1.0
  docs/docsite/rst/porting_guides/porting_guide_10.rst
Labels: backport-2.17

#1618 Add 2.18 support matrix entry
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: no_backport

#1617 Update playbooks_loops.rst
  docs/docsite/rst/playbook_guide/playbooks_loops.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17

#1597 Update unit test document
  docs/docsite/rst/dev_guide/testing.rst
Labels: techreview, backport-2.15, backport-2.16, backport-2.17, core_approval

#1596 Replace WG list with a pointer to the forum groups .
  docs/docsite/rst/community/communication.rst
Labels: backport-2.16, backport-2.17

#1605 developing_collections_migrating.rst: update
  docs/docsite/rst/dev_guide/developing_collections_migrating.rst
Labels: backport-2.15, backport-2.16, backport-2.17

#1629 Revert "Add example /usr/bin/env python as Python interpreter (#280)"
  docs/docsite/rst/reference_appendices/interpreter_discovery.rst
  docs/docsite/rst/reference_appendices/python_3_support.rst
Labels: backport-2.16, backport-2.17

#1615 Remove latest symlink from publishing workflow
  .github/workflows/build-package-docs.yaml
Labels: tooling

#1636 fix Validate data against set criteria with Ansible doc
  docs/docsite/rst/network/user_guide/validate.rst
Labels: new_contributor

#1637 fix Ansible architecture docs
  docs/docsite/rst/dev_guide/overview_architecture.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17

#1346 Remove reference of scp_if_ssh option
  docs/docsite/rst/reference_appendices/faq.rst
Labels: backport-2.17, core_approval

#1653 Remove references to archived ansible/ansible-examples repository
  docs/docsite/rst/playbook_guide/guide_rolling_upgrade.rst
  docs/docsite/rst/playbook_guide/playbooks.rst
  docs/docsite/rst/playbook_guide/playbooks_delegation.rst
  docs/docsite/rst/playbook_guide/playbooks_intro.rst
  docs/docsite/rst/playbook_guide/playbooks_reuse.rst
  docs/docsite/rst/playbook_guide/playbooks_reuse_roles.rst
  docs/docsite/rst/playbook_guide/playbooks_variables.rst
  docs/docsite/rst/reference_appendices/YAMLSyntax.rst
  docs/docsite/rst/tips_tricks/ansible_tips_tricks.rst
  docs/docsite/rst/tips_tricks/sample_setup.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17
