Repository ansible/ansible-documentation, pull requests merged in 2024-02, with the labels that each got.

#1096 [network] update note about `gather_network_resources`
  docs/docsite/rst/network/getting_started/first_playbook.rst
Labels: new_contributor

#913 remove outdated ansible/community links
  docs/docsite/rst/community/collection_contributors/collection_release_with_branches.rst
  docs/docsite/rst/community/collection_contributors/collection_release_without_branches.rst
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/collection_development_process.rst
  docs/docsite/rst/community/contributing_maintained_collections.rst
  docs/docsite/rst/community/contributor_path.rst
  docs/docsite/rst/community/documentation_contributions.rst
  docs/docsite/rst/community/maintainers_guidelines.rst
  docs/docsite/rst/community/maintainers_workflow.rst
  docs/docsite/rst/community/steering/community_steering_committee.rst
  docs/docsite/rst/community/steering/steering_committee_membership.rst
  docs/docsite/rst/dev_guide/developing_modules_in_groups.rst
  docs/docsite/rst/dev_guide/testing.rst
  docs/docsite/rst/dev_guide/testing_httptester.rst
  docs/docsite/rst/dev_guide/testing_integration.rst
  docs/docsite/rst/roadmap/COLLECTIONS_9.rst
  docs/docsite/rst/roadmap/ansible_core_roadmap_index.rst
Labels: sc_approval

#1057 Add documentation for module option context
  docs/docsite/rst/dev_guide/developing_program_flow_modules.rst
Labels: no_backport

#1074 Fix doc prompts
  docs/docsite/rst/network/getting_started/first_inventory.rst
  docs/docsite/rst/network/user_guide/network_debug_troubleshooting.rst
  docs/docsite/rst/network/user_guide/validate.rst
Labels: backport-2.16

#1111 Alternatives is plural
  docs/docsite/rst/dev_guide/module_lifecycle.rst
Labels: backport-2.15, backport-2.16

#1124 Update Ansible 9 porting guide
  docs/docsite/rst/porting_guides/porting_guide_9.rst
Labels: backport-2.16

#1126 Improve role argspec documentation
  docs/docsite/rst/playbook_guide/playbooks_reuse_roles.rst
Labels: backport-2.15, backport-2.16

#1053 Add example around ansible-galaxy command
  docs/docsite/rst/command_guide/cheatsheet.rst
Labels: new_contributor, backport-2.16

#1113 Fix core deprecation cycle example to match reality
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.16

#1128 Remove/update incorrect docs building documentation
  docs/docsite/Makefile
  docs/docsite/rst/community/documentation_contributions.rst
  docs/docsite/rst/dev_guide/testing_documentation.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#1143 steering committee: update members / past members lists
  docs/docsite/rst/community/steering/community_steering_committee.rst
  docs/docsite/rst/community/steering/steering_committee_past_members.rst
Labels: sc_approval, backport-2.16

#1119 Add note explaining injected task has always tag
  docs/docsite/rst/playbook_guide/playbooks_reuse_roles.rst
Labels: backport-2.15, new_contributor, backport-2.16

#1115 Fix syntax error in error condition
  docs/docsite/rst/conf.py
Labels: backport-2.15, backport-2.14, new_contributor, backport-2.16

#1114 Commented out ellipsis in YAML inventory samples
  docs/docsite/rst/inventory_guide/intro_inventory.rst
Labels: backport-2.15, backport-2.14, backport-2.16

#1099 Update playbooks_templating_now.rst
  docs/docsite/rst/playbook_guide/playbooks_templating_now.rst
Labels: new_contributor, backport-2.16

#1138 Fix problems with example inventory in the intro_patterns doc
  docs/docsite/rst/inventory_guide/intro_patterns.rst
Labels: new_contributor, backport-2.16

#1168 Add Ansible community 9.3.0 porting guide
  docs/docsite/rst/porting_guides/porting_guide_9.rst
Labels: backport-2.16

#1085 [Needs SC vote] Steering Committee: votes on new members to be conducted on the forum; change the chairperson election procedure
  docs/docsite/rst/community/steering/steering_committee_membership.rst
Labels: sc_approval
