Repository ansible/ansible-documentation, pull requests merged in 2024-09, with the labels that each got.

#1814 add check-deploy job to publish workflow
  .github/workflows/build-package-docs.yaml
Labels: doc builds, no_backport, tooling

#1828 community_steering_committee.rst: fix collection requirements link
  docs/docsite/rst/community/steering/community_steering_committee.rst
Labels: backport-2.15, sc_approval, backport-2.16, backport-2.17

#1837 Bump antsibull-docs to 2.14.0
  tests/constraints.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: backport-2.15, backport-2.16, backport-2.17

#1853 Add porting guide for Ansible 10.4.0
  docs/docsite/rst/porting_guides/porting_guide_10.rst
Labels: backport-2.17

#1854 Add porting guide for Ansible 9.10.0
  docs/docsite/rst/porting_guides/porting_guide_9.rst
Labels: backport-2.16, backport-2.17

#1852 Restore community ee content
  docs/docsite/rst/getting_started_ee/build_execution_environment.rst
  docs/docsite/rst/getting_started_ee/index.rst
  docs/docsite/rst/getting_started_ee/introduction.rst
  docs/docsite/rst/getting_started_ee/run_community_ee_image.rst
  docs/docsite/rst/getting_started_ee/run_execution_environment.rst
  docs/docsite/rst/getting_started_ee/setup_environment.rst
  docs/docsite/rst/getting_started_ee/yaml/execution-environment.yml
  docs/docsite/rst/getting_started_ee/yaml/hosts.yml
  docs/docsite/rst/getting_started_ee/yaml/test_localhost.yml
  docs/docsite/rst/getting_started_ee/yaml/test_remote.yml
Labels: backport-2.15, backport-2.16, backport-2.17

#1851 Replace communication links with a link to communication guide, part 1
  docs/docsite/rst/command_guide/intro_adhoc.rst
  docs/docsite/rst/community/getting_started.rst
  docs/docsite/rst/plugins/become.rst
  docs/docsite/rst/plugins/cache.rst
  docs/docsite/rst/plugins/callback.rst
  docs/docsite/rst/plugins/cliconf.rst
Labels: backport-2.15, backport-2.16, backport-2.17

#1863 ci: add workflow to create core tags automatically
  .github/workflows/tag.yml
Labels: no_backport, tooling

#1760 Correct information about plugin enabling
  docs/docsite/rst/dev_guide/developing_locally.rst
  docs/docsite/rst/plugins/cache.rst
  docs/docsite/rst/plugins/callback.rst
  docs/docsite/rst/plugins/inventory.rst
  docs/docsite/rst/plugins/vars.rst
Labels: backport-2.16, backport-2.17

#1764 Add documentation for loop_control option to stop a loop early
  docs/docsite/rst/playbook_guide/playbooks_loops.rst
Labels: no_backport

#1877 Change Getting started EE guide reference to point to the relevant location
  docs/docsite/rst/collections_guide/collections_installing.rst
  docs/docsite/rst/command_guide/index.rst
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/dev_guide/developing_collections_structure.rst
  docs/docsite/rst/installation_guide/intro_installation.rst
  docs/docsite/rst/shared_snippets/basic_concepts.txt
  docs/docsite/rst/tips_tricks/ansible_tips_tricks.rst
Labels: sc_approval

#1820 Revamp Windows docs
  docs/docsite/rst/installation_guide/installation_distros.rst
  docs/docsite/rst/os_guide/index.rst
  docs/docsite/rst/os_guide/intro_windows.rst
  docs/docsite/rst/os_guide/windows_dsc.rst
  docs/docsite/rst/os_guide/windows_faq.rst
  docs/docsite/rst/os_guide/windows_setup.rst
  docs/docsite/rst/os_guide/windows_ssh.rst
  docs/docsite/rst/os_guide/windows_winrm.rst
  docs/docsite/rst/os_guide/windows_winrm_certificate.rst
  docs/docsite/rst/os_guide/windows_winrm_kerberos.rst
  docs/docsite/rst/os_guide/yaml/winrm_cert_auth_setup.yaml
  docs/docsite/rst/user_guide/windows_faq.rst
  docs/docsite/rst/user_guide/windows_setup.rst
Labels: no_backport

#1892 Fix Ansible 11 roadmap
  docs/docsite/rst/roadmap/COLLECTIONS_11.rst
Labels: sc_approval

#1894 Add caveat about installing collections from git
  docs/docsite/rst/shared_snippets/installing_collections_git_repo.txt
Labels: backport-2.15, backport-2.16, backport-2.17

#1869 Nightly builds for package docs publishing workflow
  .github/workflows/build-package-docs.yaml
Labels: doc builds, no_backport, tooling

#1908 [stable-2.17] pr_labeler: re-architect triager script (#1882)
  .github/workflows/labeler.yml
  hacking/pr_labeler/.gitignore
  hacking/pr_labeler/label.py
  hacking/pr_labeler/pr_labeler/__init__.py
  hacking/pr_labeler/pr_labeler/__main__.py
  hacking/pr_labeler/pr_labeler/actions.py
  hacking/pr_labeler/pr_labeler/cli.py
  hacking/pr_labeler/pr_labeler/cli_context.py
  hacking/pr_labeler/pr_labeler/constants.py
  hacking/pr_labeler/pr_labeler/data/docs_team_info.md
  hacking/pr_labeler/pr_labeler/data/no_body_nag.md
  hacking/pr_labeler/pr_labeler/data/porting_guide_changes.md
  hacking/pr_labeler/pr_labeler/github_utils.py
  hacking/pr_labeler/pr_labeler/jinja.py
  hacking/pr_labeler/pr_labeler/py.typed
  hacking/pr_labeler/pr_labeler/utils.py
  hacking/pr_labeler/pyproject.toml
  hacking/pr_labeler/requirements.txt
  noxfile.py
  tests/pr_labeler.in
  tests/pr_labeler.txt
  tests/typing.txt
Labels: backport-2.15, backport-2.14, backport-2.16

#1848 nox: add actionlint to lint Github Actions workflows
  .github/workflows/build-package-docs.yaml
  .github/workflows/reusable-nox.yml
  .github/workflows/reusable-pip-compile.yml
  README.md
  noxfile.py
Labels: merge_commit

#1915 Update other_tools_and_programs.rst
  docs/docsite/rst/community/other_tools_and_programs.rst
Labels: new_contributor

#1924 getting_started_ee/build_execution_environment.rst: temporary sample fix
  docs/docsite/rst/getting_started_ee/build_execution_environment.rst
Labels: backport-2.16, backport-2.17

#1938 many: Fix title case of Git references
  CONTRIBUTING.md
  docs/docsite/rst/collections_guide/collections_installing.rst
  docs/docsite/rst/community/collection_contributors/collection_release_with_branches.rst
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/documentation_contributions.rst
  docs/docsite/rst/community/maintainers_workflow.rst
  docs/docsite/rst/community/other_tools_and_programs.rst
  docs/docsite/rst/dev_guide/developing_collections_contributing.rst
  docs/docsite/rst/dev_guide/developing_collections_creating.rst
  docs/docsite/rst/dev_guide/developing_collections_distributing.rst
  docs/docsite/rst/dev_guide/developing_collections_shared.rst
  docs/docsite/rst/dev_guide/developing_collections_structure.rst
  docs/docsite/rst/dev_guide/developing_modules_in_groups.rst
  docs/docsite/rst/dev_guide/developing_rebasing.rst
  docs/docsite/rst/dev_guide/testing.rst
  docs/docsite/rst/dev_guide/testing/sanity/integration-aliases.rst
  docs/docsite/rst/dev_guide/testing_httptester.rst
  docs/docsite/rst/dev_guide/testing_integration.rst
  docs/docsite/rst/dev_guide/testing_running_locally.rst
  docs/docsite/rst/galaxy/user_guide.rst
  docs/docsite/rst/inventory_guide/connection_details.rst
  docs/docsite/rst/inventory_guide/intro_inventory.rst
  docs/docsite/rst/reference_appendices/faq.rst
  docs/docsite/rst/reference_appendices/glossary.rst
  hacking/README.md
  hacking/ticket_stubs/README.md
Labels: sc_approval, backport-2.16, backport-2.17, backport-2.18

#1943 Add Ansible 11 porting guide
  docs/docsite/rst/porting_guides/porting_guide_11.rst
  docs/docsite/rst/porting_guides/porting_guides.rst
Labels: backport-2.18

#1951 dev gitiginore: sync with ansible core
  .gitignore
Labels: no_backport

#1945 fix 2.18 python requirement version
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.18

#1929 playbooks_filters: Mention the usage of the ansible.builtin.split filter
  docs/docsite/rst/playbook_guide/playbooks_filters.rst
Labels: backport-2.16, backport-2.17, backport-2.18
