Repository ansible/ansible-documentation, pull requests merged in 2024-11, with the labels that each got.

#2089 Change 2.18 to correct version
  docs/docsite/rst/conf.py
Labels: no_backport, Release Day!

#2090 update version switcher for 2.18
  docs/docsite/rst/conf.py
Labels: backport-2.16, backport-2.17, backport-2.18, Release Day!

#2108 Update ansible-core 2.18 and Ansible 11 porting guides
  docs/docsite/rst/porting_guides/porting_guide_11.rst
  docs/docsite/rst/porting_guides/porting_guide_core_2.18.rst
Labels: backport-2.18

#2113 Update Ansible 11 porting guide for 11.0.0b2
  docs/docsite/rst/porting_guides/porting_guide_11.rst
Labels: backport-2.18

#2092 add note and link for galaxy.yml details
  docs/docsite/rst/dev_guide/developing_collections_distributing.rst
Labels: backport-2.15, backport-2.16, backport-2.17, backport-2.18

#2126 build_execution_environment: add working version of Fedora
  docs/docsite/rst/getting_started_ee/yaml/execution-environment.yml
Labels: backport-2.16, backport-2.17, backport-2.18

#2132 comment the extra banner to remove community survey
  docs/docsite/.templates/banner.html
Labels: backport-2.17, backport-2.18

#2135 Add porting guide for Ansible 11.0.0rc1
  docs/docsite/rst/porting_guides/porting_guide_11.rst
Labels: backport-2.18

#2130 update pip compile dev workflow for 2.18
  .github/workflows/pip-compile-dev.yml
  MAINTAINERS.md
Labels: no_backport, tooling, merge_commit

#2142 fix: Remove stray reference to group_by_module
  docs/docsite/rst/playbook_guide/playbooks_conditionals.rst
  docs/docsite/rst/playbook_guide/playbooks_variables.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17, backport-2.18

#2161 Fix the misspelled word 'not'
  docs/docsite/rst/dev_guide/developing_collections_structure.rst
Labels: backport-2.16, backport-2.17, backport-2.18

#2160 update latest doc version to 11
  docs/docsite/rst/conf.py
Labels: no_backport

#2120 Remove string conversion action documentation reference
  docs/docsite/rst/dev_guide/developing_program_flow_modules.rst
Labels: new_contributor, no_backport

#2119 Update some info on distribution servers
  docs/docsite/rst/dev_guide/developing_collections_distributing.rst
Labels: backport-2.15, backport-2.16, backport-2.17, backport-2.18

#2184 update release table with 2.15 EOL
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.15, backport-2.16, backport-2.17, backport-2.18

#2183 update backport instructions
  docs/docsite/rst/community/development_process.rst
Labels: backport-2.16, backport-2.17, backport-2.18

#2192 fix bad formating
  docs/docsite/rst/dev_guide/developing_collections_distributing.rst
Labels: backport-2.16, backport-2.17, backport-2.18

#2193 LICENSE and DCO in CODEOWNERS for doc maintainers
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport-2.15, backport-2.14, backport-2.13, backport-2.16, backport-2.17, backport-2.18

#2159 update version switcher for Ansible 11
  docs/docsite/rst/conf.py
Labels: backport-2.16, backport-2.17, backport-2.18

#2158 update release table for Ansible 11
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.16, backport-2.17, backport-2.18

#2213 fix anisble 11 changelog link
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: new_contributor, backport-2.18

#2212 update intersphinx links for Ansible 11
  docs/docsite/rst/conf.py
Labels: backport-2.18

#2219 Update docs build depenencies to anstibull-docs 2.16.1
  tests/constraints.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: no_backport

#2220 Update docs build dependencies for antsibull-docs 2.16.1
  tests/constraints.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: no_backport
