Repository ansible/ansible-documentation, pull requests merged in 2025-07, with the labels that each got.

#2491 Announce Ansible 11 lifetime extension
  docs/docsite/rst/roadmap/COLLECTIONS_11.rst
Labels: sc_approval, backport-2.18, backport-2.19

#2791 Adds Porting Guide for 12.0.0a9
  docs/docsite/rst/porting_guides/porting_guide_12.rst
Labels: backport-2.19

#2687 fix option for _ANSIBLE_TEMPLAR_UNTRUSTED_TEMPLATE_BEHAVIOR
  docs/docsite/rst/porting_guides/porting_guide_core_2.19.rst
Labels: techreview, backport-2.19

#2745 Use antsibull-docutils 1.2.0 to simplify rst-yamllint checker
  tests/checkers/rst-yamllint.py
  tests/pr_labeler.txt
  tests/requirements.in
  tests/requirements.txt
  tests/typing.in
  tests/typing.txt
Labels: backport-2.19

#2812 Moves boolean table to module docs
  docs/docsite/rst/module_plugin_guide/modules_intro.rst
  docs/docsite/rst/playbook_guide/playbooks_variables.rst
Labels: backport-2.17, backport-2.18, backport-2.19

#2833 Add more International Communities
  docs/docsite/rst/community/communication.rst
Labels: backport-2.17, backport-2.18, backport-2.19

#2846 Correct year of contingency date to create ansible-build-data for Ansible 13
  docs/docsite/rst/roadmap/COLLECTIONS_12.rst
Labels: sc_approval, new_contributor, backport-2.19

#2639 porting guide 2.19 - describe lazy complex var eval impact on builtin filters/tests
  docs/docsite/rst/porting_guides/porting_guide_core_2.19.rst
Labels: backport-2.19

#2810 core-2.19 prep - update versioning
  docs/docsite/rst/conf.py
Labels: backport-2.17, backport-2.18, backport-2.19

#2821 Update removal/readd processes to refer to the documentation of ansible-build-data
  docs/docsite/rst/community/collection_contributors/collection_package_removal.rst
Labels: backport-2.17, backport-2.18, backport-2.19

#2848 Code block languages: normalize casing of `yaml` and `yaml+jinja`, update list in style guide, add comments to keep lists in sync
  docs/docsite/rst/dev_guide/developing_plugins.rst
  docs/docsite/rst/dev_guide/sidecar.rst
  docs/docsite/rst/dev_guide/style_guide/index.rst
  docs/docsite/rst/module_plugin_guide/plugin_filtering_config.rst
  docs/docsite/rst/playbook_guide/complex_data_manipulation.rst
  docs/docsite/rst/playbook_guide/playbooks_blocks.rst
  docs/docsite/rst/playbook_guide/playbooks_module_defaults.rst
  docs/docsite/rst/plugins/filter.rst
  docs/docsite/rst/plugins/lookup.rst
  docs/docsite/rst/plugins/test.rst
  tests/checkers/rst-yamllint.py
Labels: backport-2.18, backport-2.19

#2868 dev_guide/style_guide/spelling_word_choice.rst: See vs Refer to
  docs/docsite/rst/dev_guide/style_guide/spelling_word_choice.rst
Labels: backport-2.17, backport-2.18, backport-2.19

#2886 update backport instructions
  docs/docsite/rst/community/development_process.rst
Labels: backport-2.17, backport-2.18, backport-2.19

#2813 add details on some plugin options - AI-assisted
  docs/docsite/rst/dev_guide/developing_plugins.rst
Labels: backport-2.17, backport-2.18, backport-2.19

#2654 Document Windows App Control Feature
  docs/docsite/rst/os_guide/intro_windows.rst
  docs/docsite/rst/os_guide/windows_app_control.rst
  examples/scripts/New-AnsiblePowerShellSignature.ps1
Labels: backport-2.19

#2799 community/maintainers_workflow.rst: improve wording and formatting
  docs/docsite/rst/community/maintainers_workflow.rst
Labels: backport-2.17, backport-2.18, backport-2.19

#2934 update for control node min. python 3.12 now
  .github/workflows/labeler.yml
  .github/workflows/pip-compile-dev.yml
  .readthedocs.yaml
  docs/docsite/rst/dev_guide/testing/sanity/compile.rst
  noxfile.py
Labels: no_backport
