Repository ansible/ansible-documentation, pull requests merged in 2025-01, with the labels that each got.

#2317 Bump antsibull-docs to 2.16.2
  tests/constraints.in
  tests/requirements-relaxed.txt
  tests/requirements.txt
Labels: backport-2.16, backport-2.17, backport-2.18

#2318 intro_bsd: Update docs for the current FreeBSD and OpenBSD
  docs/docsite/rst/os_guide/intro_bsd.rst
Labels: new_contributor, backport-2.18

#2329 remove 2.9 from version switcher
  docs/docsite/rst/conf.py
Labels: backport-2.17, backport-2.18

#2332 Fix(style-guide): Add definition for "ID" abbreviation in spelling and word choice guide
  docs/docsite/rst/dev_guide/style_guide/spelling_word_choice.rst
Labels: backport-2.15, new_contributor, backport-2.16, backport-2.17, backport-2.18

#2333 callback event reception order
  docs/docsite/rst/plugins/callback.rst
Labels: backport-2.15, backport-2.16, backport-2.17, backport-2.18

#2141 Update platform_junos.rst
  docs/docsite/rst/network/user_guide/platform_junos.rst
Labels: techreview, backport-2.17, backport-2.18

#2346 How Can I Help? page: add a ref to collections quick-start guide
  docs/docsite/rst/community/how_can_I_help.rst
Labels: backport-2.18

#2322 add runpip instructions for dependencies
  docs/docsite/rst/installation_guide/intro_installation.rst
Labels: new_contributor, backport-2.16, backport-2.17, backport-2.18

#2353 Remove the relaxed requirements
  .github/workflows/pip-compile-docs.yml
  docs/docsite/rst/community/documentation_contributions.rst
  noxfile.py
  tests/constraints-base.in
  tests/constraints.in
  tests/requirements-relaxed.in
  tests/requirements-relaxed.txt
  tests/requirements.in
  tests/requirements.txt
Labels: backport-2.16, tooling, backport-2.17, backport-2.18

#2368 [stable-2.18] remove tag session from noxfile
  noxfile.py
Labels: tooling

#2367 Bump antsibull-docs to 2.16.3
  tests/constraints.in
  tests/requirements.txt
Labels: backport-2.16, backport-2.17, backport-2.18

#2376 Skip auto-generated porting guides for rstcheck
  tests/checkers.py
  tests/checkers/rstcheck.json
Labels: backport-2.16, backport-2.17, backport-2.18

#2380 Update Ansible 11 porting guide for 11.2.0 release
  docs/docsite/rst/porting_guides/porting_guide_11.rst
Labels: backport-2.18
