Repository ansible/ansible-documentation, pull requests merged in 2025-05, with the labels that each got.

#2586 Update networking jumphost examples
  docs/docsite/rst/network/user_guide/network_debug_troubleshooting.rst
  docs/docsite/rst/network/user_guide/platform_ce.rst
  docs/docsite/rst/network/user_guide/platform_cnos.rst
  docs/docsite/rst/network/user_guide/platform_dellos10.rst
  docs/docsite/rst/network/user_guide/platform_dellos6.rst
  docs/docsite/rst/network/user_guide/platform_dellos9.rst
  docs/docsite/rst/network/user_guide/platform_enos.rst
  docs/docsite/rst/network/user_guide/platform_eos.rst
  docs/docsite/rst/network/user_guide/platform_eric_eccli.rst
  docs/docsite/rst/network/user_guide/platform_exos.rst
  docs/docsite/rst/network/user_guide/platform_frr.rst
  docs/docsite/rst/network/user_guide/platform_icx.rst
  docs/docsite/rst/network/user_guide/platform_ios.rst
  docs/docsite/rst/network/user_guide/platform_iosxr.rst
  docs/docsite/rst/network/user_guide/platform_ironware.rst
  docs/docsite/rst/network/user_guide/platform_junos.rst
  docs/docsite/rst/network/user_guide/platform_netvisor.rst
  docs/docsite/rst/network/user_guide/platform_nos.rst
  docs/docsite/rst/network/user_guide/platform_nxos.rst
  docs/docsite/rst/network/user_guide/platform_routeros.rst
  docs/docsite/rst/network/user_guide/platform_slxos.rst
  docs/docsite/rst/network/user_guide/platform_voss.rst
  docs/docsite/rst/network/user_guide/platform_vyos.rst
  docs/docsite/rst/network/user_guide/platform_weos4.rst
Labels: backport-2.18, backport-2.19

#2576 porting guide 2.19: async_status started/finished
  docs/docsite/rst/porting_guides/porting_guide_core_2.19.rst
Labels: backport-2.19

#2566 First pass at adding notes requested in #1638
  docs/docsite/rst/playbook_guide/playbooks_vars_facts.rst
Labels: backport-2.16, backport-2.17, backport-2.18, backport-2.19

#2552 Only run pr_labeler on devel or stable-* branches
  .github/workflows/labeler.yml
Labels: backport-2.15, backport-2.14, backport-2.16, backport-2.17, backport-2.18, backport-2.19

#2438 Update interpreter_discovery for changes made in ansible-core 2.17
  docs/docsite/rst/reference_appendices/interpreter_discovery.rst
Labels: techreview, new_contributor, backport-2.17, backport-2.18

#2612 remove some yaml code-block items to fix CI
  docs/docsite/rst/playbook_guide/playbooks_filters.rst
Labels: no_backport

#2613 Add Ansible 12.0.0a3 porting guide
  docs/docsite/rst/porting_guides/porting_guide_12.rst
Labels: backport-2.19

#2615 Ansible 12 porting guide: use correct underlines for subsubsections
  docs/docsite/rst/porting_guides/porting_guide_12.rst
Labels: backport-2.19

#2617 Fix docs build
  docs/docsite/rst/reference_appendices/module_utils.rst
Labels: backport-2.19

#2630 Add 12.0.0a4 porting guide
  docs/docsite/rst/porting_guides/porting_guide_12.rst
Labels: backport-2.19

#2628 add 12 porting guide to the index
  docs/docsite/rst/porting_guides/porting_guides.rst
Labels: backport-2.19

#2634 Fix inputs in the deploy workflow
  .github/workflows/reusable-deploy-docs.yaml
Labels: doc builds, no_backport

#2632 maintainer_guidelines: update
  docs/docsite/rst/community/maintainers_guidelines.rst
Labels: backport-2.18, backport-2.19

#2618 [backport] for PR #2404 and #2612
  docs/docsite/rst/playbook_guide/playbooks_filters.rst
Labels: no_backport

#2646 Add Ansible 11.6.0 porting guide
  docs/docsite/rst/porting_guides/porting_guide_11.rst
Labels: backport-2.18, backport-2.19

#2585 collection_requirements: add requirements version specification recommendation to avoid conflicts when building EEs
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
Labels: sc_approval

#2573 The callback yaml is deprecated.
  docs/docsite/rst/os_guide/intro_bsd.rst
Labels: new_contributor, backport-2.17, backport-2.18, backport-2.19
