Repository ansible/ansible-documentation, pull requests merged in 2025-08, with the labels that each got.

#2936 missed a few python 3.12 updates
  .github/workflows/pip-compile-docs.yml
  .github/workflows/reusable-nox.yml
Labels: no_backport

#2965 [stable-2.19] compile sanity test: update supported Python versions
  docs/docsite/rst/dev_guide/testing/sanity/compile.rst
Labels: backport-2.18

#2968 [stable-2.15] Fix supported Python list for 2.15
  docs/docsite/rst/dev_guide/testing/sanity/compile.rst
Labels: backport-2.14

#2980 Harmonize formatting of group names in docs/docsite/rst/inventory_guide/intro_inventory.rst
  docs/docsite/rst/inventory_guide/intro_inventory.rst
Labels: documentation, new_contributor, backport-2.17, backport-2.18, backport-2.19
