Repository ansible/ansible-documentation, pull requests merged in 2025-02, with the labels that each got.

#2388 Remove incorrect parts from docs
  docs/docsite/rst/network/user_guide/cli_parsing.rst
Labels: backport-2.16, backport-2.17, backport-2.18

#2392 Add SC member forum names
  docs/docsite/rst/community/steering/community_steering_committee.rst
Labels: sc_approval, backport-2.17, backport-2.18

#2366 Update ticketing stubs
  hacking/ticket_stubs/README.md
  hacking/ticket_stubs/bug_internal_api.md
  hacking/ticket_stubs/bug_wrong_repo.md
  hacking/ticket_stubs/collections.md
  hacking/ticket_stubs/guide_newbie_about_gh_and_contributing_to_ansible.md
  hacking/ticket_stubs/no_thanks.md
  hacking/ticket_stubs/pr_duplicate.md
  hacking/ticket_stubs/pr_merged.md
  hacking/ticket_stubs/proposal.md
  hacking/ticket_stubs/question_not_bug.md
  hacking/ticket_stubs/resolved.md
  hacking/ticket_stubs/wider_discussion.md
Labels: no_backport

#2372 intro_inventory: Update ignore extension setting
  docs/docsite/rst/inventory_guide/intro_inventory.rst
Labels: backport-2.16, backport-2.17, backport-2.18

#2409 [stable-2.18] Bump wntrblm/nox from 2024.10.09 to 2025.02.09
  .github/workflows/reusable-nox.yml
Labels: dependency_update

#2410 [stable-2.17] Bump wntrblm/nox from 2024.10.09 to 2025.02.09
  .github/workflows/reusable-nox.yml
Labels: dependency_update

#2411 [stable-2.16] Bump wntrblm/nox from 2024.10.09 to 2025.02.09
  .github/workflows/reusable-nox.yml
Labels: dependency_update

#2412 Fix broken link markup
  docs/docsite/rst/community/steering/steering_committee_membership.rst
Labels: sc_approval, backport-2.16, backport-2.17, backport-2.18

#2408 Fix YAML syntax, adjust more code block languages
  docs/docsite/rst/collections_guide/collections_using_playbooks.rst
  docs/docsite/rst/dev_guide/developing_collections_creating.rst
  docs/docsite/rst/dev_guide/migrating_roles.rst
  docs/docsite/rst/dev_guide/style_guide/index.rst
  docs/docsite/rst/inventory/implicit_localhost.rst
  docs/docsite/rst/inventory_guide/connection_details.rst
  docs/docsite/rst/network/dev_guide/developing_resource_modules_network.rst
  docs/docsite/rst/network/getting_started/first_inventory.rst
  docs/docsite/rst/network/user_guide/cli_parsing.rst
  docs/docsite/rst/network/user_guide/network_debug_troubleshooting.rst
  docs/docsite/rst/network/user_guide/network_resource_modules.rst
  docs/docsite/rst/network/user_guide/platform_ce.rst
  docs/docsite/rst/network/user_guide/platform_iosxr.rst
  docs/docsite/rst/network/user_guide/platform_junos.rst
  docs/docsite/rst/network/user_guide/platform_netconf_enabled.rst
  docs/docsite/rst/os_guide/intro_bsd.rst
  docs/docsite/rst/os_guide/windows_usage.rst
  docs/docsite/rst/playbook_guide/playbooks_advanced_syntax.rst
  docs/docsite/rst/playbook_guide/playbooks_debugger.rst
  docs/docsite/rst/playbook_guide/playbooks_filters.rst
  docs/docsite/rst/playbook_guide/playbooks_loops.rst
  docs/docsite/rst/playbook_guide/playbooks_reuse_roles.rst
  docs/docsite/rst/playbook_guide/playbooks_tags.rst
  docs/docsite/rst/playbook_guide/playbooks_tests.rst
  docs/docsite/rst/playbook_guide/playbooks_variables.rst
  docs/docsite/rst/playbook_guide/shared_snippets/role_directory.txt
  docs/docsite/rst/plugins/filter.rst
  docs/docsite/rst/plugins/vars.rst
  docs/docsite/rst/porting_guides/porting_guide_2.0.rst
  docs/docsite/rst/porting_guides/porting_guide_2.5.rst
  docs/docsite/rst/reference_appendices/faq.rst
  docs/docsite/rst/tips_tricks/shared_snippets/role_directory.txt
Labels: backport-2.18

#2425 Update Ansible 11 porting guide for 11.3.0 release
  docs/docsite/rst/porting_guides/porting_guide_11.rst
Labels: backport-2.18
