Repository ansible/ansible-documentation, pull requests merged in 2025-04, with the labels that each got.

#2499 ci: use official create-github-app-token action
  .github/workflows/labeler.yml
  .github/workflows/reusable-pip-compile.yml
  .github/workflows/tag.yml
Labels: tooling, needs_manual_backport

#2504 [stable-2.17] ci: use official create-github-app-token action (#2499)
  .github/workflows/labeler.yml
Labels: tooling

#2505 [stable-2.16] ci: use official create-github-app-token action (#2499)
  .github/workflows/labeler.yml
Labels: tooling

#2506 [stable-2.15] ci: use official create-github-app-token action (#2499)
  .github/workflows/labeler.yml
Labels: tooling

#2507 [stable-2.14] ci: use official create-github-app-token action (#2499)
  .github/workflows/labeler.yml
Labels: tooling

#2508 Adjust Ansible 12 roadmap
  docs/docsite/rst/roadmap/COLLECTIONS_12.rst
Labels: sc_approval

#2522 [stable 2.19] Updating new branch
  .github/workflows/build-package-docs.yaml
  .github/workflows/pip-compile-dev.yml
  .github/workflows/pip-compile-docs.yml
  .github/workflows/reusable-pip-compile.yml
  .github/workflows/tag.yml
  docs/ansible-core-branch.txt
  hacking/tagger/tag.py
  noxfile.py
  tests/tag.in
  tests/tag.txt
  tests/typing.in
  tests/typing.txt
Labels: tooling

#2525 Add 12 to package docs build workflow
  .github/workflows/build-package-docs.yaml
Labels: doc builds, no_backport, tooling

#2524 Update core support matrix 2.19
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: techreview, backport-2.19

#2527 Add porting guide for Ansible 12.0.0a1
  docs/docsite/rst/porting_guides/porting_guide_12.rst
Labels: backport-2.19

#2523 update devel workflows for stable-2.19
  .github/workflows/pip-compile-dev.yml
  hacking/tagger/tag.py
Labels: no_backport, tooling

#2532 Apply Ansible 12 porting guide fix
  docs/docsite/rst/porting_guides/porting_guide_12.rst
Labels: backport-2.19

#2547 Update Ansible 11 porting guide for 11.5.0 release
  docs/docsite/rst/porting_guides/porting_guide_11.rst
Labels: backport-2.19

#2551 Update developing_modules_documenting.rst
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
Labels: backport-2.17, backport-2.18, backport-2.19

#2541 Update example image from `fedora:39` to `fedora:42`
  docs/docsite/rst/getting_started_ee/yaml/execution-environment.yml
Labels: backport-2.17, backport-2.18, backport-2.19

#2560 porting_guide_core_2.19.rst: add clatifications on the required non-string key conversion
  docs/docsite/rst/porting_guides/porting_guide_core_2.19.rst
Labels: backport-2.19

#2470 Add one sentence per line to the style guide
  docs/docsite/rst/dev_guide/style_guide/basic_rules.rst
  docs/docsite/rst/dev_guide/style_guide/grammar_punctuation.rst
Labels: backport-2.17, backport-2.18, backport-2.19

#2574 add EXAMPLE to sample passwords etc
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
Labels: backport-2.17, backport-2.18, backport-2.19

#2486 Build and deploy from the devel branch once a week, preferably at the…
  .github/workflows/build-devel-docs.yaml
  .github/workflows/build-latest-docs.yaml
Labels: doc builds, no_backport
