Repository ansible/ansible-documentation, pull requests merged in 2025-06, with the labels that each got.

#2679 update 2.19 roadmap for extended beta
  docs/docsite/rst/roadmap/ROADMAP_2_19.rst
Labels: backport-2.19

#2418 Extension for Ansible redirects
  .github/workflows/build-package-docs.yaml
  .github/workflows/reusable-build-docs.yaml
  docs/docsite/.templates/redirect_template.html
  docs/docsite/Makefile.sphinx
  docs/docsite/declarative-configs/ansible_redirects.toml
  docs/docsite/rst/conf.py
  tests/requirements.in
  tests/requirements.txt
Labels: doc builds, backport-2.18, backport-2.19

#2664 Adjust Ansible 12's release schedule to ansible-core 2.19's updated schedule
  docs/docsite/rst/roadmap/COLLECTIONS_12.rst
Labels: sc_approval, backport-2.19

#2663 unreachable hosts do not execute the always section either
  docs/docsite/rst/playbook_guide/playbooks_blocks.rst
Labels: backport-2.19

#2666 ansible-core versioning scheme docs
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.16, backport-2.17, backport-2.18, backport-2.19

#2706 Fix core banner
  docs/docsite/.templates/banner.html
Labels: backport-2.19

#2708 Update intro_inventory.rst
  docs/docsite/rst/inventory_guide/intro_inventory.rst
Labels: backport-2.16, backport-2.17, backport-2.18, backport-2.19

#2678 Collection requirements: declare that Galaxy artifacts must not be deleted once they appear in Ansible releases
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
Labels: sc_approval, backport-2.18, backport-2.19

#2721 Update windows_winrm.rst
  docs/docsite/rst/os_guide/windows_winrm.rst
Labels: new_contributor, backport-2.18, backport-2.19

#2732 Add Ansible 11.7.0 porting guide
  docs/docsite/rst/porting_guides/porting_guide_11.rst
Labels: backport-2.18, backport-2.19

#2761 Update Ansible 12 porting guide for 12.0.0a7 release
  docs/docsite/rst/porting_guides/porting_guide_12.rst
Labels: backport-2.19

#2753 Move Ansible markup documentation to a separate page
  docs/docsite/rst/dev_guide/ansible_index.rst
  docs/docsite/rst/dev_guide/ansible_markup.rst
  docs/docsite/rst/dev_guide/core_index.rst
  docs/docsite/rst/dev_guide/developing_modules_documenting.rst
  docs/docsite/rst/playbook_guide/playbooks_reuse_roles.rst
Labels: backport-2.18, backport-2.19
