Repository ansible/ansible-documentation, pull requests merged in 2025-03, with the labels that each got.

#2348 Restructure package docs workflow
  .github/workflows/build-package-docs.yaml
  .github/workflows/reusable-build-docs.yaml
  .github/workflows/reusable-deploy-docs.yaml
Labels: doc builds, no_backport, tooling

#2430 Restore default values for scheduled builds
  .github/workflows/build-package-docs.yaml
Labels: doc builds, no_backport

#2432 pr_labeler: fix error in pyproject.toml
  hacking/pr_labeler/pyproject.toml
Labels: backport-2.16, backport-2.17, backport-2.18

#2440 Remove thaumos from SC
  docs/docsite/rst/community/steering/community_steering_committee.rst
  docs/docsite/rst/community/steering/steering_committee_past_members.rst
Labels: sc_approval

#2393 Involuntarily leaving SC: Allow PM on forum
  docs/docsite/rst/community/steering/steering_committee_membership.rst
Labels: sc_approval, backport-2.17, backport-2.18

#2424 Introduce a new section for managing z/OS UNIX mainframe hosts with Ansible.
  docs/docsite/rst/os_guide/index.rst
  docs/docsite/rst/os_guide/intro_zos.rst
  docs/docsite/rst/reference_appendices/faq.rst
Labels: new_contributor

#2421 Porting guide entry for become timeout is unreachable error
  docs/docsite/rst/porting_guides/porting_guide_core_2.19.rst
Labels: no_backport

#2417 fix label warnings
  docs/docsite/rst/ansible_index.rst
  docs/docsite/rst/community/collection_contributors/collection_requirements.rst
  docs/docsite/rst/community/maintainers_guidelines.rst
  docs/docsite/rst/community/steering/community_steering_committee.rst
  docs/docsite/rst/dev_guide/ansible_index.rst
  docs/docsite/rst/dev_guide/core_index.rst
  docs/docsite/rst/dev_guide/developing_modules_general.rst
  docs/docsite/rst/network/user_guide/network_debug_troubleshooting.rst
  docs/docsite/rst/reference_appendices/logging.rst
  docs/docsite/rst/reference_appendices/python_3_support.rst
  docs/docsite/rst/roadmap/ansible_core_roadmap_index.rst
  docs/docsite/rst/roadmap/ansible_roadmap_index.rst
  docs/docsite/rst/roadmap/old_roadmap_index.rst
Labels: sc_approval

#2428 Recommend madbg instead of epdb
  docs/docsite/rst/dev_guide/debugging.rst
Labels: new_contributor

#2464 add fest banner
  docs/docsite/.templates/banner.html
Labels: backport-2.16, backport-2.17, backport-2.18

#2468 Add Ansible 11.4.0 porting guide
  docs/docsite/rst/porting_guides/porting_guide_11.rst
Labels: backport-2.18

#2477 ci pip-compile: always create PR when one doesn't exist
  .github/workflows/reusable-pip-compile.yml
Labels: no_backport, tooling

#2472 update the pip-compile details in the readme
  README.md
Labels: backport-2.16, backport-2.17, backport-2.18

#2478 Fix codespell issues
  .codespellignorewords
  docs/docsite/Makefile
  docs/docsite/rst/os_guide/windows_performance.rst
  docs/docsite/rst/playbook_guide/playbooks_reuse.rst
  docs/docsite/rst/playbook_guide/playbooks_startnstep.rst
  docs/docsite/rst/user_guide/playbooks_reuse.rst
Labels: backport-2.16, tooling, backport-2.17, backport-2.18
