Repository ansible/ansible-documentation, pull requests merged in 2025-09, with the labels that each got.

#3023 docs: fix typos and clarify wording in community docs
  CONTRIBUTING.md
  examples/DOCUMENTATION.yml
  examples/README.md
Labels: new_contributor, backport-2.17, backport-2.18, backport-2.19

#3008 community/maintainers_workflow.rst: improve wording and formatting
  docs/docsite/rst/community/contributor_path.rst
  docs/docsite/rst/community/maintainers_workflow.rst
Labels: backport-2.16, backport-2.17, backport-2.18, backport-2.19

#2964 update latest version to Ansible 12
  docs/docsite/rst/conf.py
Labels: backport-2.18, backport-2.19

#3050 add core 2.19 docs to package docs
  docs/docsite/.templates/banner.html
Labels: backport-2.19

#3053 bump latest to 12 in the scheduled docs build
  .github/workflows/build-latest-docs.yaml
Labels: doc builds, no_backport

#3064 Fixed #3063
  .github/workflows/pip-compile-dev.yml
Labels: no_backport

#3075 Add ansible-core 2.20 to maintenance info
  docs/docsite/rst/reference_appendices/release_and_maintenance.rst
Labels: backport-2.20
